CREATE OR REPLACE PACKAGE PKG_FACTURA_PROVEEDOR_DETALLE AS
    TYPE T_CURSOR IS REF CURSOR;
 
    PROCEDURE SP_INSERTAR_DETALLE (
        P_ID_FACTURA_PROVEEDOR IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROVEEDOR%TYPE,
        P_ID_ARTICULO          IN CP_FACTURA_PROVEEDOR_DETALLE.ID_ARTICULO%TYPE,
        P_DESCRIPCION          IN CP_FACTURA_PROVEEDOR_DETALLE.DESCRIPCION%TYPE,
        P_CANTIDAD             IN CP_FACTURA_PROVEEDOR_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_UNITARIO      IN CP_FACTURA_PROVEEDOR_DETALLE.PRECIO_UNITARIO%TYPE,
        P_ID_UNIDAD_MEDIDA     IN CP_FACTURA_PROVEEDOR_DETALLE.ID_UNIDAD_MEDIDA%TYPE,
        P_ID_DETALLE_OUT       OUT CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE
    );
 
    PROCEDURE SP_LISTAR_DETALLE (
        P_ID_FACTURA_PROVEEDOR IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROVEEDOR%TYPE DEFAULT NULL,
        P_CURSOR OUT T_CURSOR
    );
 
    PROCEDURE SP_OBTENER_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE,
        P_CURSOR OUT T_CURSOR
    );
 
    PROCEDURE SP_ACTUALIZAR_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE,
        P_ID_ARTICULO             IN CP_FACTURA_PROVEEDOR_DETALLE.ID_ARTICULO%TYPE,
        P_DESCRIPCION             IN CP_FACTURA_PROVEEDOR_DETALLE.DESCRIPCION%TYPE,
        P_CANTIDAD                IN CP_FACTURA_PROVEEDOR_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_UNITARIO         IN CP_FACTURA_PROVEEDOR_DETALLE.PRECIO_UNITARIO%TYPE,
        P_ID_UNIDAD_MEDIDA        IN CP_FACTURA_PROVEEDOR_DETALLE.ID_UNIDAD_MEDIDA%TYPE
    );
 
    PROCEDURE SP_ELIMINAR_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE
    );
END PKG_FACTURA_PROVEEDOR_DETALLE;
/
CREATE OR REPLACE PACKAGE BODY PKG_FACTURA_PROVEEDOR_DETALLE AS
 
    PROCEDURE SP_INSERTAR_DETALLE (
        P_ID_FACTURA_PROVEEDOR IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROVEEDOR%TYPE,
        P_ID_ARTICULO          IN CP_FACTURA_PROVEEDOR_DETALLE.ID_ARTICULO%TYPE,
        P_DESCRIPCION          IN CP_FACTURA_PROVEEDOR_DETALLE.DESCRIPCION%TYPE,
        P_CANTIDAD             IN CP_FACTURA_PROVEEDOR_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_UNITARIO      IN CP_FACTURA_PROVEEDOR_DETALLE.PRECIO_UNITARIO%TYPE,
        P_ID_UNIDAD_MEDIDA     IN CP_FACTURA_PROVEEDOR_DETALLE.ID_UNIDAD_MEDIDA%TYPE,
        P_ID_DETALLE_OUT       OUT CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE
    ) IS
    BEGIN
        INSERT INTO CP_FACTURA_PROVEEDOR_DETALLE
            (ID_FACTURA_PROVEEDOR, ID_ARTICULO, DESCRIPCION, CANTIDAD, PRECIO_UNITARIO, ID_UNIDAD_MEDIDA, SUBTOTAL)
        VALUES
            (P_ID_FACTURA_PROVEEDOR, P_ID_ARTICULO, P_DESCRIPCION, P_CANTIDAD, P_PRECIO_UNITARIO, P_ID_UNIDAD_MEDIDA,
             P_CANTIDAD * P_PRECIO_UNITARIO)
        RETURNING ID_FACTURA_PROV_DETALLE INTO P_ID_DETALLE_OUT;
        COMMIT;
    END SP_INSERTAR_DETALLE;
 
    PROCEDURE SP_LISTAR_DETALLE (
        P_ID_FACTURA_PROVEEDOR IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROVEEDOR%TYPE DEFAULT NULL,
        P_CURSOR OUT T_CURSOR
    ) IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT ID_FACTURA_PROV_DETALLE, ID_FACTURA_PROVEEDOR, ID_ARTICULO,
                   DESCRIPCION, CANTIDAD, PRECIO_UNITARIO, ID_UNIDAD_MEDIDA, SUBTOTAL
            FROM CP_FACTURA_PROVEEDOR_DETALLE
            WHERE P_ID_FACTURA_PROVEEDOR IS NULL OR ID_FACTURA_PROVEEDOR = P_ID_FACTURA_PROVEEDOR
            ORDER BY ID_FACTURA_PROV_DETALLE DESC;
    END SP_LISTAR_DETALLE;
 
    PROCEDURE SP_OBTENER_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE,
        P_CURSOR OUT T_CURSOR
    ) IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT ID_FACTURA_PROV_DETALLE, ID_FACTURA_PROVEEDOR, ID_ARTICULO,
                   DESCRIPCION, CANTIDAD, PRECIO_UNITARIO, ID_UNIDAD_MEDIDA, SUBTOTAL
            FROM CP_FACTURA_PROVEEDOR_DETALLE
            WHERE ID_FACTURA_PROV_DETALLE = P_ID_FACTURA_PROV_DETALLE;
    END SP_OBTENER_DETALLE;
 
    PROCEDURE SP_ACTUALIZAR_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE,
        P_ID_ARTICULO             IN CP_FACTURA_PROVEEDOR_DETALLE.ID_ARTICULO%TYPE,
        P_DESCRIPCION             IN CP_FACTURA_PROVEEDOR_DETALLE.DESCRIPCION%TYPE,
        P_CANTIDAD                IN CP_FACTURA_PROVEEDOR_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_UNITARIO         IN CP_FACTURA_PROVEEDOR_DETALLE.PRECIO_UNITARIO%TYPE,
        P_ID_UNIDAD_MEDIDA        IN CP_FACTURA_PROVEEDOR_DETALLE.ID_UNIDAD_MEDIDA%TYPE
    ) IS
    BEGIN
        UPDATE CP_FACTURA_PROVEEDOR_DETALLE
        SET ID_ARTICULO = P_ID_ARTICULO,
            DESCRIPCION = P_DESCRIPCION,
            CANTIDAD = P_CANTIDAD,
            PRECIO_UNITARIO = P_PRECIO_UNITARIO,
            ID_UNIDAD_MEDIDA = P_ID_UNIDAD_MEDIDA,
            SUBTOTAL = P_CANTIDAD * P_PRECIO_UNITARIO
        WHERE ID_FACTURA_PROV_DETALLE = P_ID_FACTURA_PROV_DETALLE;
        COMMIT;
    END SP_ACTUALIZAR_DETALLE;
 
    PROCEDURE SP_ELIMINAR_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE
    ) IS
    BEGIN
        DELETE FROM CP_FACTURA_PROVEEDOR_DETALLE WHERE ID_FACTURA_PROV_DETALLE = P_ID_FACTURA_PROV_DETALLE;
        COMMIT;
    END SP_ELIMINAR_DETALLE;
 
END PKG_FACTURA_PROVEEDOR_DETALLE;
/
