CREATE OR REPLACE PACKAGE PKG_TIPO_UNIDAD_MEDIDA AS
    TYPE T_CURSOR IS REF CURSOR;
    PROCEDURE SP_LISTAR_UNIDADES_MEDIDA (P_CURSOR OUT T_CURSOR);
END PKG_TIPO_UNIDAD_MEDIDA;
/
CREATE OR REPLACE PACKAGE BODY PKG_TIPO_UNIDAD_MEDIDA AS
    PROCEDURE SP_LISTAR_UNIDADES_MEDIDA (P_CURSOR OUT T_CURSOR) IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT ID_UNIDAD_MEDIDA, DESCRIPCION
            FROM CP_TIPO_UNIDAD_MEDIDA
            ORDER BY DESCRIPCION;
    END SP_LISTAR_UNIDADES_MEDIDA;
END PKG_TIPO_UNIDAD_MEDIDA;
/
