-- ============================================================================
-- DATOS DE PRUEBA: Cajas Chicas (CP_CAJA_CHICA) - 16 cajas, una por sucursal
-- Modulo: Cuentas por Pagar (CXP) - Caja Chica
-- Base de Datos: Oracle 12c+
--
-- Requiere: database/DEPENDENCIAS_EXTERNAS/RUN_DEPENDENCIAS.sql ya ejecutado.
--   Las sucursales (SUC-001..SUC-016) y los empleados responsables
--   (EMP-001..EMP-016) son de Nomina y se cargan ahi, no en este archivo.
--   Aqui solo se buscan por su CODIGO.
--
-- Re-ejecutable: cada caja se inserta solo si su sucursal aun no tiene caja.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CAJAS CHICAS (16 Cajas con montos realistas y estados para probar UX)
-- ----------------------------------------------------------------------------

-- Caja 1: Central Zona 1 (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-001'),
    2500.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-001'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 2: Pradera Zona 10 (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-002'),
    3000.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-002'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 3: Oficinas Centrales Reforma (Activa - Fondo corporativo)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-003'),
    12000.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-003'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 4: Miraflores Zona 11 (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-004'),
    3500.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-004'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 5: Oakland Mall Zona 10 (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-005'),
    4000.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-005'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 6: Portales Zona 17 (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-006'),
    2000.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-006'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 7: Pradera Concepción (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-007'),
    5000.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-007'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 8: Naranjo Mall Mixco (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-008'),
    2800.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-008'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 9: Peri-Roosevelt Zona 7 (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-009'),
    3200.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-009'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 10: Pacific Center Zona 11 (Inactiva - para probar pestaña Inactivas)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-010'),
    1500.00, 'I', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-010'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 11: Quetzaltenango Mont Blanc (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-011'),
    6000.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-011'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 12: Escuintla Palmeras (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-012'),
    4500.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-012'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 13: Antigua Guatemala Santa Inés (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-013'),
    3800.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-013'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 14: Cobán Plaza Magdalena (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-014'),
    4200.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-014'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 15: Mazatenango Las Américas (Activa)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-015'),
    2500.00, 'A', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-015'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

-- Caja 16: Chiquimula Pradera (Inactiva - para probar pestaña Inactivas)
INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
SELECT S.ID_SUCURSAL,
    (SELECT ID_EMPLEADO FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-016'),
    1800.00, 'I', 'N'
FROM NOM_SUCURSAL S
WHERE S.CODIGO = 'SUC-016'
  AND NOT EXISTS (SELECT 1 FROM CP_CAJA_CHICA C WHERE C.ID_SUCURSAL = S.ID_SUCURSAL);

COMMIT;
