-- ============================================================================
-- SCRIPT MAESTRO: Cuentas por Pagar (CxP) - Setup completo y ordenado
-- ============================================================================
-- Consolida TODO lo que el backend necesita: tablas + paquetes PL/SQL, en el
-- orden correcto de dependencias (FK), a partir de lo que ya esta vivo hoy
-- en la base de datos (confirmado contra los handlers de backend/src) mas lo
-- que faltaba por guardar como script.
--
-- SEGURO DE RE-EJECUTAR sobre una base de datos que YA tiene datos reales:
--   - Cada CREATE TABLE esta protegido: si la tabla ya existe (ORA-00955) lo
--     ignora en vez de fallar o borrar nada. NO hay ningun DROP TABLE aqui.
--   - Los paquetes usan CREATE OR REPLACE PACKAGE (no tocan filas).
--
-- Este archivo NO inserta NINGUN dato (ni catalogos ni pruebas) a proposito:
-- los datos de prueba de CxP viven en database/RUN_ALL_SEEDS.sql y los de
-- otros modulos en database/DEPENDENCIAS_EXTERNAS/02_DATOS_DEPENDENCIAS.sql.
--
-- Solo contiene objetos de Cuentas por Pagar (tablas CP_*, vista y paquetes).
-- Las tablas de otros modulos de las que depende (Nomina, Compras,
-- Inventarios) viven aparte en database/DEPENDENCIAS_EXTERNAS/.
--
-- Orden de ejecucion de TODO el proyecto, de cero (ver database/Pasos.SQL.txt):
--   0. database/SCRIPT_GENERAL.sql                          -> modelo completo
--   1. database/DEPENDENCIAS_EXTERNAS/RUN_DEPENDENCIAS.sql  -> tablas y datos de otros modulos
--   2. Este archivo (00_MASTER_SETUP.sql)                   -> estructura y codigo de CxP
--   3. database/RUN_ALL_SEEDS.sql                           -> datos de prueba de CxP
-- ============================================================================


-- ============================================================================
-- FASE 1: Verificacion de dependencias externas
-- Las tablas de OTROS modulos que Cuentas por Pagar necesita (NOM_SUCURSAL,
-- NOM_EMPLEADO, PROVEEDOR, ARTICULO...) ya NO se crean aqui: las crea
-- database/DEPENDENCIAS_EXTERNAS/RUN_DEPENDENCIAS.sql (temporal, hasta que
-- Nomina / Compras / Inventarios entreguen las suyas). Si falta alguna, este
-- archivo se detiene aqui para no dejar paquetes invalidos ni llaves sin crear.
-- ============================================================================

WHENEVER SQLERROR EXIT FAILURE
DECLARE
    L_FALTAN VARCHAR2(4000);
BEGIN
    FOR T IN (
        SELECT COLUMN_VALUE AS NOMBRE
        FROM TABLE(SYS.ODCIVARCHAR2LIST('NOM_DEPARTAMENTO', 'NOM_PUESTO', 'NOM_SUCURSAL', 'NOM_EMPLEADO',
                                        'PROVEEDOR', 'CATEGORIA_ARTICULO', 'ARTICULO'))
        WHERE COLUMN_VALUE NOT IN (SELECT TABLE_NAME FROM USER_TABLES)
    ) LOOP
        L_FALTAN := L_FALTAN || ' ' || T.NOMBRE;
    END LOOP;
    IF L_FALTAN IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20000,
            'Faltan tablas de otros modulos:' || L_FALTAN ||
            '. Ejecute primero database/DEPENDENCIAS_EXTERNAS/RUN_DEPENDENCIAS.sql');
    END IF;
END;
/
WHENEVER SQLERROR CONTINUE


-- ============================================================================
-- FASE 2: Nucleo de Cuentas por Pagar (prefijo CP_) - esquema simple, el que
-- realmente esta vivo hoy (confirmado: /api/cheques, /api/contrasenas-pago,
-- /api/facturas-proveedor, /api/retenciones, /api/unidades-medida ya
-- responden 200 contra estas tablas).
-- ============================================================================

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CP_TIPO_UNIDAD_MEDIDA (
        ID_UNIDAD_MEDIDA NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        DESCRIPCION VARCHAR2(100) NOT NULL,
        CONSTRAINT PK_CP_TIPO_UNIDAD_MEDIDA PRIMARY KEY (ID_UNIDAD_MEDIDA)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CP_FACTURA_PROVEEDOR (
        ID_FACTURA_PROVEEDOR NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        ID_PROVEEDOR NUMBER NOT NULL,
        TIPO_DOCUMENTO VARCHAR2(20) NOT NULL CHECK (TIPO_DOCUMENTO IN (''FACTURA'',''FACTURA_ESPECIAL'',''NOTA_CREDITO'',''NOTA_DEBITO'')),
        NUMERO_DTE VARCHAR2(50),
        SERIE_DTE VARCHAR2(50),
        FECHA_EMISION DATE NOT NULL,
        FECHA_DOCUMENTO DATE NOT NULL,
        FECHA_VENCIMIENTO DATE,
        MONTO_TOTAL NUMBER(14,2) NOT NULL,
        MONTO_RETENCION_IVA NUMBER(14,2) DEFAULT 0,
        MONTO_RETENCION_ISR NUMBER(14,2) DEFAULT 0,
        SALDO_PENDIENTE NUMBER(14,2) NOT NULL,
        ESTADO VARCHAR2(20) DEFAULT ''PENDIENTE'',
        ID_FACTURA_REFERENCIA NUMBER,
        NOTAS VARCHAR2(300),
        CONSTRAINT PK_CP_FACTURA_PROVEEDOR PRIMARY KEY (ID_FACTURA_PROVEEDOR),
        CONSTRAINT CK_CP_FACTURA_ESTADO CHECK (ESTADO IN (''PENDIENTE'',''PAGADA_PARCIAL'',''PAGADA'',''APLICADA'',''ANULADA''))
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CP_FACTURA_PROVEEDOR_DETALLE (
        ID_FACTURA_PROV_DETALLE NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        ID_FACTURA_PROVEEDOR NUMBER NOT NULL,
        ID_ARTICULO NUMBER,
        DESCRIPCION VARCHAR2(300) NOT NULL,
        CANTIDAD NUMBER(14,2) DEFAULT 1,
        PRECIO_UNITARIO NUMBER(14,4) NOT NULL,
        ID_UNIDAD_MEDIDA NUMBER,
        SUBTOTAL NUMBER(14,2) NOT NULL,
        CONSTRAINT PK_CP_FACT_PROV_DETALLE PRIMARY KEY (ID_FACTURA_PROV_DETALLE)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CP_RETENCION (
        ID_RETENCION NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        ID_FACTURA_PROVEEDOR NUMBER NOT NULL,
        TIPO_RETENCION VARCHAR2(10) NOT NULL CHECK (TIPO_RETENCION IN (''IVA'',''ISR'')),
        BASE_IMPONIBLE NUMBER(14,2) NOT NULL,
        PORCENTAJE NUMBER(5,2) NOT NULL,
        MONTO NUMBER(14,2) NOT NULL,
        NUMERO_CONSTANCIA VARCHAR2(50),
        CONSTRAINT PK_CP_RETENCION PRIMARY KEY (ID_RETENCION)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CP_CONTRASENA_PAGO (
        ID_CONTRASENA NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        ID_FACTURA_PROVEEDOR NUMBER NOT NULL,
        FECHA DATE NOT NULL,
        FORMA_PAGO VARCHAR2(20) NOT NULL CHECK (FORMA_PAGO IN (''CHEQUE'',''TRANSFERENCIA'',''EFECTIVO'')),
        ESTADO VARCHAR2(20) DEFAULT ''PENDIENTE'' CHECK (ESTADO IN (''PENDIENTE'',''EMITIDA'',''PAGADA'',''ANULADA'')),
        MONTO NUMBER(14,2) NOT NULL,
        ID_EMPLEADO_AUTORIZA NUMBER,
        NOTAS VARCHAR2(300),
        CONSTRAINT PK_CP_CONTRASENA_PAGO PRIMARY KEY (ID_CONTRASENA)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CP_CHEQUE (
        ID_CHEQUE NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        ID_CONTRASENA_PAGO NUMBER NOT NULL,
        BANCO VARCHAR2(50) NOT NULL,
        NUMERO_CHEQUE VARCHAR2(20) NOT NULL,
        FECHA_EMISION DATE NOT NULL,
        FECHA_COBRO DATE,
        ESTADO VARCHAR2(20) DEFAULT ''EMITIDO'' CHECK (ESTADO IN (''EMITIDO'',''COBRADO'',''ANULADO'')),
        CONSTRAINT PK_CP_CHEQUE PRIMARY KEY (ID_CHEQUE)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- CP_CAJA_CHICA: tabla maestra REAL de caja chica (la que ya usa
-- CP_PKG_CAJA_CHICA_MOVIMIENTO). Incluye columnas de borrado logico porque
-- PKG_CAJA_CHICA (mas abajo) las necesita.
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CP_CAJA_CHICA (
        ID_CAJA_CHICA NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        ID_SUCURSAL NUMBER NOT NULL,
        ID_EMPLEADO_RESPONSABLE NUMBER NOT NULL,
        FONDO_ASIGNADO NUMBER(10,2) NOT NULL,
        ESTADO CHAR(1) DEFAULT ''A'' CHECK (ESTADO IN (''A'',''I'')),
        ELIMINADO CHAR(1) DEFAULT ''N'' NOT NULL CHECK (ELIMINADO IN (''S'',''N'')),
        FECHA_ELIMINACION TIMESTAMP,
        ELIMINADO_POR NUMBER,
        CONSTRAINT PK_CP_CAJA_CHICA PRIMARY KEY (ID_CAJA_CHICA)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Si CP_CAJA_CHICA ya existia SIN las columnas de borrado logico (version
-- de 00_esquema_cxp.sql), se agregan aqui sin tocar las filas existentes.
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA ADD (ELIMINADO CHAR(1) DEFAULT ''N'' NOT NULL)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA ADD (FECHA_ELIMINACION TIMESTAMP)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA ADD (ELIMINADO_POR NUMBER)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CP_CAJA_CHICA_MOVIMIENTO (
        ID_MOVIMIENTO_CAJA NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        ID_CAJA_CHICA NUMBER NOT NULL,
        FECHA DATE NOT NULL,
        TIPO_MOVIMIENTO VARCHAR2(20) NOT NULL CHECK (TIPO_MOVIMIENTO IN (''REPOSICION'',''GASTO'',''ANULADO'')),
        CONCEPTO VARCHAR2(300) NOT NULL,
        MONTO NUMBER(10,2) NOT NULL,
        NUMERO_COMPROBANTE VARCHAR2(50),
        CONSTRAINT PK_CP_CAJA_CHICA_MOVIMIENTO PRIMARY KEY (ID_MOVIMIENTO_CAJA)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Si la tabla ya existia sin 'ANULADO' en el CHECK de TIPO_MOVIMIENTO (asi la
-- crea SCRIPT_GENERAL.sql), se reemplaza ese CHECK por CK_CP_CCM_TIPO_MOVIMIENTO.
-- El CHECK original no tiene nombre fijo (SYS_C...): se busca por su contenido.
-- (Sustituye a CajaChicaMovimiento/FIX_CHECK_CONSTRAINT_ANULADO.sql.)
DECLARE
    L_COND VARCHAR2(32767);
BEGIN
    FOR C IN (SELECT CONSTRAINT_NAME, SEARCH_CONDITION FROM USER_CONSTRAINTS
              WHERE TABLE_NAME = 'CP_CAJA_CHICA_MOVIMIENTO' AND CONSTRAINT_TYPE = 'C') LOOP
        L_COND := C.SEARCH_CONDITION;
        IF INSTR(L_COND, 'REPOSICION') > 0 AND INSTR(L_COND, 'ANULADO') = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA_MOVIMIENTO DROP CONSTRAINT "' || C.CONSTRAINT_NAME || '"';
        END IF;
    END LOOP;
END;
/
DECLARE
    L_COND VARCHAR2(32767);
BEGIN
    -- Solo se agrega si ningun CHECK actual ya acepta 'ANULADO'.
    FOR C IN (SELECT SEARCH_CONDITION FROM USER_CONSTRAINTS
              WHERE TABLE_NAME = 'CP_CAJA_CHICA_MOVIMIENTO' AND CONSTRAINT_TYPE = 'C') LOOP
        L_COND := C.SEARCH_CONDITION;
        IF INSTR(L_COND, 'ANULADO') > 0 THEN
            RETURN;
        END IF;
    END LOOP;
    EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA_MOVIMIENTO ADD CONSTRAINT CK_CP_CCM_TIPO_MOVIMIENTO CHECK (TIPO_MOVIMIENTO IN (''REPOSICION'',''GASTO'',''ANULADO''))';
END;
/


-- ============================================================================
-- FASE 2.5: Limpieza de FKs heredadas de una version anterior del esquema
-- (la que tenia PROVEEDOR, ARTICULO y EMPLEADO/SUCURSAL SIN prefijo NOM_).
-- Si tu base de datos se creo con esa version vieja antes de migrar a este
-- script, las tablas CP_* de la Fase 2 pueden haber quedado con FKs viejas
-- apuntando a esas tablas (que ya no existen en este diseño, o quedaron
-- vacias porque ningun seed les inserta datos). Esas FKs viejas bloquean
-- CUALQUIER insert valido en RUN_ALL_SEEDS.sql con ORA-02291, sin importar
-- el ID que uses. Aqui las eliminamos si existen; si tu base ya esta limpia
-- (nunca corriste la version vieja), esto no hace nada.
-- ============================================================================

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_FACTURA_PROVEEDOR DROP CONSTRAINT FK_CP_FACTURA_PROVEEDOR_1'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_FACTURA_PROVEEDOR_DETALLE DROP CONSTRAINT FK_CP_FACT_PROV_DET_2'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CONTRASENA_PAGO DROP CONSTRAINT FK_CP_CONTRASENA_PAGO_2'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA DROP CONSTRAINT FK_CP_CAJA_CHICA_1'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA DROP CONSTRAINT FK_CP_CAJA_CHICA_2'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/


-- ============================================================================
-- FASE 3: Llaves foraneas (todas las tablas de la Fase 2 ya existen)
-- ============================================================================

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_FACTURA_PROVEEDOR_DETALLE ADD CONSTRAINT FK_CP_FACT_PROV_DET_1 FOREIGN KEY (ID_FACTURA_PROVEEDOR) REFERENCES CP_FACTURA_PROVEEDOR(ID_FACTURA_PROVEEDOR)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_FACTURA_PROVEEDOR_DETALLE ADD CONSTRAINT FK_DETALLE_UNIDAD_MEDIDA FOREIGN KEY (ID_UNIDAD_MEDIDA) REFERENCES CP_TIPO_UNIDAD_MEDIDA(ID_UNIDAD_MEDIDA)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_RETENCION ADD CONSTRAINT FK_CP_RETENCION_1 FOREIGN KEY (ID_FACTURA_PROVEEDOR) REFERENCES CP_FACTURA_PROVEEDOR(ID_FACTURA_PROVEEDOR)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CONTRASENA_PAGO ADD CONSTRAINT FK_CP_CONTRASENA_PAGO_1 FOREIGN KEY (ID_FACTURA_PROVEEDOR) REFERENCES CP_FACTURA_PROVEEDOR(ID_FACTURA_PROVEEDOR)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CHEQUE ADD CONSTRAINT FK_CP_CHEQUE_1 FOREIGN KEY (ID_CONTRASENA_PAGO) REFERENCES CP_CONTRASENA_PAGO(ID_CONTRASENA)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA ADD CONSTRAINT FK_CP_CAJA_CHICA_SUC FOREIGN KEY (ID_SUCURSAL) REFERENCES NOM_SUCURSAL(ID_SUCURSAL)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA ADD CONSTRAINT FK_CP_CAJA_CHICA_EMP FOREIGN KEY (ID_EMPLEADO_RESPONSABLE) REFERENCES NOM_EMPLEADO(ID_EMPLEADO)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CAJA_CHICA_MOVIMIENTO ADD CONSTRAINT FK_CP_CAJA_CHICA_MOV_1 FOREIGN KEY (ID_CAJA_CHICA) REFERENCES CP_CAJA_CHICA(ID_CAJA_CHICA)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ============================================================================
-- FASE 3.5: Notas de credito/debito y vista de facturas
-- (re-ejecutable: cada paso ignora el error si ya estaba aplicado)
-- ============================================================================

-- Notas de la contrasena de pago: guarda el motivo escrito al anularla
-- (igual que Caja Chica Movimiento exige un motivo de anulacion).
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_CONTRASENA_PAGO ADD (NOTAS VARCHAR2(300))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- Factura a la que se aplica una NOTA_CREDITO / NOTA_DEBITO.
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_FACTURA_PROVEEDOR ADD (ID_FACTURA_REFERENCIA NUMBER)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_FACTURA_PROVEEDOR ADD CONSTRAINT FK_CP_FACTURA_REFERENCIA FOREIGN KEY (ID_FACTURA_REFERENCIA) REFERENCES CP_FACTURA_PROVEEDOR(ID_FACTURA_PROVEEDOR)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2275, -2264) THEN RAISE; END IF; END;
/

-- Notas del documento: guarda el motivo escrito al anularlo
-- (igual que Caja Chica Movimiento exige un motivo de anulacion).
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_FACTURA_PROVEEDOR ADD (NOTAS VARCHAR2(300))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- Estado APLICADA (notas de credito/debito ya aplicadas a su factura).
-- El CHECK original no tiene nombre fijo (SYS_C...), asi que se busca por su
-- contenido y se reemplaza por uno con nombre (CK_CP_FACTURA_ESTADO).
DECLARE
    L_COND VARCHAR2(32767);
BEGIN
    FOR C IN (SELECT CONSTRAINT_NAME, SEARCH_CONDITION FROM USER_CONSTRAINTS
              WHERE TABLE_NAME = 'CP_FACTURA_PROVEEDOR' AND CONSTRAINT_TYPE = 'C'
                AND CONSTRAINT_NAME != 'CK_CP_FACTURA_ESTADO') LOOP
        L_COND := C.SEARCH_CONDITION;
        IF INSTR(L_COND, 'PAGADA_PARCIAL') > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE CP_FACTURA_PROVEEDOR DROP CONSTRAINT "' || C.CONSTRAINT_NAME || '"';
        END IF;
    END LOOP;
END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CP_FACTURA_PROVEEDOR ADD CONSTRAINT CK_CP_FACTURA_ESTADO CHECK (ESTADO IN (''PENDIENTE'',''PAGADA_PARCIAL'',''PAGADA'',''APLICADA'',''ANULADA''))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2264 THEN RAISE; END IF; END;
/

-- Vista de facturas con proveedor, notas aplicadas y pagos emitidos
-- (la usan SP_LISTAR_FACTURAS / SP_OBTENER_FACTURA). Requiere la tabla
-- PROVEEDOR (DEPENDENCIAS_EXTERNAS o SCRIPT_GENERAL.sql).
CREATE OR REPLACE VIEW VW_CP_FACTURA_PROVEEDOR AS
SELECT F.ID_FACTURA_PROVEEDOR,
       F.ID_PROVEEDOR,
       P.NIT AS NIT_PROVEEDOR,
       P.RAZON_SOCIAL AS NOMBRE_PROVEEDOR,
       F.TIPO_DOCUMENTO,
       F.NUMERO_DTE,
       F.SERIE_DTE,
       F.FECHA_EMISION,
       F.FECHA_DOCUMENTO,
       F.FECHA_VENCIMIENTO,
       F.MONTO_TOTAL,
       F.MONTO_RETENCION_IVA,
       F.MONTO_RETENCION_ISR,
       F.SALDO_PENDIENTE,
       F.ESTADO,
       F.ID_FACTURA_REFERENCIA,
       F.NOTAS,
       NVL(N.MONTO_NC, 0) AS MONTO_NOTAS_CREDITO,
       NVL(N.MONTO_ND, 0) AS MONTO_NOTAS_DEBITO,
       NVL(N.NOTAS_ACTIVAS, 0) AS NOTAS_ACTIVAS,
       NVL(C.MONTO_PAGADO, 0) AS MONTO_PAGADO,
       NVL(C.CONTRASENAS_ACTIVAS, 0) AS CONTRASENAS_ACTIVAS
FROM CP_FACTURA_PROVEEDOR F
LEFT JOIN PROVEEDOR P ON P.ID_PROVEEDOR = F.ID_PROVEEDOR
LEFT JOIN (
    SELECT ID_FACTURA_REFERENCIA,
           SUM(CASE WHEN TIPO_DOCUMENTO = 'NOTA_CREDITO' THEN MONTO_TOTAL END) AS MONTO_NC,
           SUM(CASE WHEN TIPO_DOCUMENTO = 'NOTA_DEBITO' THEN MONTO_TOTAL END) AS MONTO_ND,
           COUNT(*) AS NOTAS_ACTIVAS
    FROM CP_FACTURA_PROVEEDOR
    WHERE ID_FACTURA_REFERENCIA IS NOT NULL AND ESTADO != 'ANULADA'
    GROUP BY ID_FACTURA_REFERENCIA
) N ON N.ID_FACTURA_REFERENCIA = F.ID_FACTURA_PROVEEDOR
LEFT JOIN (
    SELECT ID_FACTURA_PROVEEDOR,
           SUM(CASE WHEN ESTADO IN ('EMITIDA', 'PAGADA') THEN MONTO END) AS MONTO_PAGADO,
           SUM(CASE WHEN ESTADO != 'ANULADA' THEN 1 ELSE 0 END) AS CONTRASENAS_ACTIVAS
    FROM CP_CONTRASENA_PAGO
    GROUP BY ID_FACTURA_PROVEEDOR
) C ON C.ID_FACTURA_PROVEEDOR = F.ID_FACTURA_PROVEEDOR;


-- ============================================================================
-- FASE 4: Paquetes PL/SQL (CREATE OR REPLACE = no toca ninguna fila,
-- seguro de correr las veces que quieras)
-- ============================================================================

-- ---- PKG_CP_FACTURA_PROVEEDOR (backend/src/handlers/facturaProveedor.handler.ts) ----
-- Reglas de la factura de proveedor:
--   * MONTO_TOTAL = suma de sus lineas de detalle (minimo una linea).
--   * MONTO_RETENCION_IVA / ISR = suma de CP_RETENCION (se registran en la vista Retenciones).
--   * Neto a pagar = total - retenciones - notas de credito + notas de debito aplicadas.
--   * SALDO_PENDIENTE = neto - pagos emitidos (contrasenas EMITIDA / PAGADA).
--   * NOTA_CREDITO / NOTA_DEBITO se aplican a una factura (ID_FACTURA_REFERENCIA),
--     no se pagan: quedan con saldo 0 y estado APLICADA.
-- SP_RECALCULAR es el UNICO lugar que calcula totales, saldo y estado; lo llaman
-- este paquete y los de contrasenas, detalle y retenciones despues de cada cambio.
-- Requiere la tabla PROVEEDOR (DEPENDENCIAS_EXTERNAS o SCRIPT_GENERAL.sql) y la vista
-- VW_CP_FACTURA_PROVEEDOR (Fase 3.5 de este archivo).
-- Codigos de error de negocio: ORA-2012x.
CREATE OR REPLACE PACKAGE PKG_CP_FACTURA_PROVEEDOR AS
    PROCEDURE SP_LISTAR_FACTURAS(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_OBTENER_FACTURA(p_id_factura IN NUMBER, p_cursor OUT SYS_REFCURSOR, p_cursor_detalle OUT SYS_REFCURSOR);
    PROCEDURE SP_LISTAR_PROVEEDORES(p_cursor OUT SYS_REFCURSOR);
    -- Crea el encabezado con total 0; las lineas se agregan despues con
    -- PKG_FACTURA_PROVEEDOR_DETALLE.SP_INSERTAR_DETALLE en la MISMA transaccion
    -- y se cierra con SP_VALIDAR_TIENE_DETALLE.
    PROCEDURE SP_INSERTAR_FACTURA(
        p_id_proveedor IN NUMBER,
        p_tipo_documento IN VARCHAR2,
        p_numero_dte IN VARCHAR2,
        p_serie_dte IN VARCHAR2,
        p_fecha_emision IN DATE,
        p_fecha_documento IN DATE,
        p_fecha_vencimiento IN DATE,
        p_id_factura_referencia IN NUMBER,
        p_id_factura_out OUT NUMBER
    );
    PROCEDURE SP_VALIDAR_TIENE_DETALLE(p_id_factura IN NUMBER);
    PROCEDURE SP_ACTUALIZAR_FACTURA(
        p_id_factura IN NUMBER,
        p_id_proveedor IN NUMBER,
        p_numero_dte IN VARCHAR2,
        p_serie_dte IN VARCHAR2,
        p_fecha_emision IN DATE,
        p_fecha_documento IN DATE,
        p_fecha_vencimiento IN DATE,
        p_id_factura_referencia IN NUMBER
    );
    -- Requiere un motivo escrito; se guarda en NOTAS.
    PROCEDURE SP_ANULAR_FACTURA(p_id_factura IN NUMBER, p_motivo IN VARCHAR2);
    -- Valida que se puedan modificar las lineas de detalle (usado por PKG_FACTURA_PROVEEDOR_DETALLE).
    PROCEDURE SP_VALIDAR_DETALLE_EDITABLE(p_id_factura IN NUMBER);
    -- Recalcula total, retenciones, saldo y estado (y los de su factura de referencia).
    PROCEDURE SP_RECALCULAR(p_id_factura IN NUMBER);
END PKG_CP_FACTURA_PROVEEDOR;
/

CREATE OR REPLACE PACKAGE BODY PKG_CP_FACTURA_PROVEEDOR AS

    FUNCTION Q(p_monto IN NUMBER) RETURN VARCHAR2 IS
    BEGIN
        RETURN 'Q' || TO_CHAR(NVL(p_monto, 0), 'FM999,999,990.00');
    END Q;

    FUNCTION ES_NOTA(p_tipo IN VARCHAR2) RETURN BOOLEAN IS
    BEGIN
        RETURN p_tipo IN ('NOTA_CREDITO', 'NOTA_DEBITO');
    END ES_NOTA;

    PROCEDURE LEER_FACTURA(p_id_factura IN NUMBER, p_row OUT CP_FACTURA_PROVEEDOR%ROWTYPE) IS
    BEGIN
        SELECT * INTO p_row FROM CP_FACTURA_PROVEEDOR
        WHERE ID_FACTURA_PROVEEDOR = p_id_factura
        FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20125, 'La factura ' || p_id_factura || ' no existe.');
    END LEER_FACTURA;

    -- Contrasenas no anuladas (PENDIENTE / EMITIDA / PAGADA) de la factura.
    FUNCTION CONTRASENAS_ACTIVAS(p_id_factura IN NUMBER) RETURN NUMBER IS
        L_N NUMBER;
    BEGIN
        SELECT COUNT(*) INTO L_N FROM CP_CONTRASENA_PAGO
        WHERE ID_FACTURA_PROVEEDOR = p_id_factura AND ESTADO != 'ANULADA';
        RETURN L_N;
    END CONTRASENAS_ACTIVAS;

    -- Notas de credito/debito no anuladas aplicadas a la factura.
    FUNCTION NOTAS_ACTIVAS(p_id_factura IN NUMBER) RETURN NUMBER IS
        L_N NUMBER;
    BEGIN
        SELECT COUNT(*) INTO L_N FROM CP_FACTURA_PROVEEDOR
        WHERE ID_FACTURA_REFERENCIA = p_id_factura AND ESTADO != 'ANULADA';
        RETURN L_N;
    END NOTAS_ACTIVAS;

    -- Validaciones comunes de encabezado (crear y editar).
    PROCEDURE VALIDAR_CABECERA(
        p_id_factura IN NUMBER,
        p_id_proveedor IN NUMBER,
        p_tipo_documento IN VARCHAR2,
        p_numero_dte IN VARCHAR2,
        p_serie_dte IN VARCHAR2,
        p_fecha_emision IN DATE,
        p_fecha_documento IN DATE,
        p_fecha_vencimiento IN DATE,
        p_id_factura_referencia IN NUMBER
    ) IS
        L_N NUMBER;
        L_REF CP_FACTURA_PROVEEDOR%ROWTYPE;
    BEGIN
        -- Proveedor activo
        SELECT COUNT(*) INTO L_N FROM PROVEEDOR WHERE ID_PROVEEDOR = p_id_proveedor AND ESTADO = 'A';
        IF L_N = 0 THEN
            RAISE_APPLICATION_ERROR(-20120, 'El proveedor ' || p_id_proveedor || ' no existe o no esta activo.');
        END IF;

        -- Serie y numero de DTE obligatorios y sin duplicar por proveedor
        IF TRIM(p_serie_dte) IS NULL OR TRIM(p_numero_dte) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20121, 'La serie y el numero de DTE son obligatorios.');
        END IF;
        SELECT COUNT(*) INTO L_N FROM CP_FACTURA_PROVEEDOR
        WHERE ID_PROVEEDOR = p_id_proveedor
          AND UPPER(TRIM(SERIE_DTE)) = UPPER(TRIM(p_serie_dte))
          AND UPPER(TRIM(NUMERO_DTE)) = UPPER(TRIM(p_numero_dte))
          AND ESTADO != 'ANULADA'
          AND ID_FACTURA_PROVEEDOR != NVL(p_id_factura, -1);
        IF L_N > 0 THEN
            RAISE_APPLICATION_ERROR(-20122,
                'Ya existe un documento del mismo proveedor con serie ' || TRIM(p_serie_dte) ||
                ' y numero ' || TRIM(p_numero_dte) || '.');
        END IF;

        -- Fechas
        IF p_fecha_emision IS NULL OR p_fecha_documento IS NULL THEN
            RAISE_APPLICATION_ERROR(-20123, 'La fecha de emision y la fecha de documento son obligatorias.');
        END IF;
        IF TRUNC(p_fecha_emision) > TRUNC(SYSDATE) THEN
            RAISE_APPLICATION_ERROR(-20123, 'La fecha de emision no puede ser futura.');
        END IF;
        IF TRUNC(p_fecha_documento) < TRUNC(p_fecha_emision) THEN
            RAISE_APPLICATION_ERROR(-20123, 'La fecha de documento no puede ser anterior a la fecha de emision.');
        END IF;
        IF p_fecha_vencimiento IS NOT NULL AND TRUNC(p_fecha_vencimiento) < TRUNC(p_fecha_emision) THEN
            RAISE_APPLICATION_ERROR(-20123, 'La fecha de vencimiento no puede ser anterior a la fecha de emision.');
        END IF;

        -- Factura de referencia: obligatoria para notas, prohibida para facturas
        IF ES_NOTA(p_tipo_documento) THEN
            IF p_id_factura_referencia IS NULL THEN
                RAISE_APPLICATION_ERROR(-20124, 'Las notas de credito y debito deben indicar la factura a la que se aplican.');
            END IF;
            BEGIN
                SELECT * INTO L_REF FROM CP_FACTURA_PROVEEDOR WHERE ID_FACTURA_PROVEEDOR = p_id_factura_referencia;
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    RAISE_APPLICATION_ERROR(-20124, 'La factura de referencia ' || p_id_factura_referencia || ' no existe.');
            END;
            IF ES_NOTA(L_REF.TIPO_DOCUMENTO) THEN
                RAISE_APPLICATION_ERROR(-20124, 'Una nota solo se puede aplicar a una FACTURA o FACTURA ESPECIAL.');
            END IF;
            IF L_REF.ESTADO = 'ANULADA' THEN
                RAISE_APPLICATION_ERROR(-20124, 'La factura de referencia ' || p_id_factura_referencia || ' esta ANULADA.');
            END IF;
            IF L_REF.ID_PROVEEDOR != p_id_proveedor THEN
                RAISE_APPLICATION_ERROR(-20124, 'La factura de referencia pertenece a otro proveedor.');
            END IF;
        ELSIF p_id_factura_referencia IS NOT NULL THEN
            RAISE_APPLICATION_ERROR(-20124, 'Solo las notas de credito y debito llevan factura de referencia.');
        END IF;
    END VALIDAR_CABECERA;

    PROCEDURE SP_RECALCULAR(p_id_factura IN NUMBER) IS
        L_F CP_FACTURA_PROVEEDOR%ROWTYPE;
        L_LINEAS NUMBER;
        L_TOTAL NUMBER;
        L_IVA NUMBER;
        L_ISR NUMBER;
        L_NC NUMBER;
        L_ND NUMBER;
        L_NETO NUMBER;
        L_PAGADO NUMBER;
        L_COMPROMETIDO NUMBER;
        L_SALDO NUMBER;
        L_ESTADO VARCHAR2(20);
    BEGIN
        LEER_FACTURA(p_id_factura, L_F);

        -- Total = suma de lineas (si una factura heredada no tiene lineas, se conserva su total)
        SELECT COUNT(*), NVL(SUM(SUBTOTAL), 0) INTO L_LINEAS, L_TOTAL
        FROM CP_FACTURA_PROVEEDOR_DETALLE WHERE ID_FACTURA_PROVEEDOR = p_id_factura;
        IF L_LINEAS = 0 THEN
            L_TOTAL := L_F.MONTO_TOTAL;
        END IF;

        SELECT NVL(SUM(CASE WHEN TIPO_RETENCION = 'IVA' THEN MONTO END), 0),
               NVL(SUM(CASE WHEN TIPO_RETENCION = 'ISR' THEN MONTO END), 0)
        INTO L_IVA, L_ISR
        FROM CP_RETENCION WHERE ID_FACTURA_PROVEEDOR = p_id_factura;

        IF ES_NOTA(L_F.TIPO_DOCUMENTO) THEN
            -- Las notas no se pagan: su efecto se refleja en la factura de referencia.
            L_SALDO := 0;
            L_ESTADO := CASE WHEN L_F.ESTADO = 'ANULADA' THEN 'ANULADA' ELSE 'APLICADA' END;
        ELSE
            SELECT NVL(SUM(CASE WHEN TIPO_DOCUMENTO = 'NOTA_CREDITO' THEN MONTO_TOTAL END), 0),
                   NVL(SUM(CASE WHEN TIPO_DOCUMENTO = 'NOTA_DEBITO' THEN MONTO_TOTAL END), 0)
            INTO L_NC, L_ND
            FROM CP_FACTURA_PROVEEDOR
            WHERE ID_FACTURA_REFERENCIA = p_id_factura AND ESTADO != 'ANULADA';

            SELECT NVL(SUM(CASE WHEN ESTADO IN ('EMITIDA', 'PAGADA') THEN MONTO END), 0),
                   NVL(SUM(CASE WHEN ESTADO = 'PENDIENTE' THEN MONTO END), 0)
            INTO L_PAGADO, L_COMPROMETIDO
            FROM CP_CONTRASENA_PAGO WHERE ID_FACTURA_PROVEEDOR = p_id_factura;

            L_NETO := L_TOTAL - L_IVA - L_ISR - L_NC + L_ND;
            L_SALDO := L_NETO - L_PAGADO;

            IF L_F.ESTADO = 'ANULADA' THEN
                L_SALDO := L_F.SALDO_PENDIENTE;
                L_ESTADO := 'ANULADA';
            ELSE
                IF L_SALDO < 0 THEN
                    RAISE_APPLICATION_ERROR(-20127,
                        'La operacion dejaria la factura ' || p_id_factura || ' con saldo negativo: neto a pagar ' ||
                        Q(L_NETO) || ' y ya se emitieron pagos por ' || Q(L_PAGADO) || '.');
                END IF;
                IF L_COMPROMETIDO > L_SALDO THEN
                    RAISE_APPLICATION_ERROR(-20128,
                        'La factura ' || p_id_factura || ' quedaria con saldo ' || Q(L_SALDO) ||
                        ', menor a sus contrasenas pendientes (' || Q(L_COMPROMETIDO) ||
                        '). Ajuste o anule esas contrasenas primero.');
                END IF;
                L_ESTADO := CASE
                                WHEN L_SALDO <= 0 THEN 'PAGADA'
                                WHEN L_PAGADO > 0 THEN 'PAGADA_PARCIAL'
                                ELSE 'PENDIENTE'
                            END;
            END IF;
        END IF;

        UPDATE CP_FACTURA_PROVEEDOR
        SET MONTO_TOTAL = L_TOTAL,
            MONTO_RETENCION_IVA = L_IVA,
            MONTO_RETENCION_ISR = L_ISR,
            SALDO_PENDIENTE = L_SALDO,
            ESTADO = L_ESTADO
        WHERE ID_FACTURA_PROVEEDOR = p_id_factura;

        -- Una nota afecta el saldo de la factura a la que se aplica.
        IF ES_NOTA(L_F.TIPO_DOCUMENTO) AND L_F.ID_FACTURA_REFERENCIA IS NOT NULL THEN
            SP_RECALCULAR(L_F.ID_FACTURA_REFERENCIA);
        END IF;
    END SP_RECALCULAR;

    PROCEDURE SP_LISTAR_FACTURAS(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT * FROM VW_CP_FACTURA_PROVEEDOR ORDER BY ID_FACTURA_PROVEEDOR DESC;
    END SP_LISTAR_FACTURAS;

    PROCEDURE SP_OBTENER_FACTURA(
        p_id_factura IN NUMBER,
        p_cursor OUT SYS_REFCURSOR,
        p_cursor_detalle OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT * FROM VW_CP_FACTURA_PROVEEDOR WHERE ID_FACTURA_PROVEEDOR = p_id_factura;
        OPEN p_cursor_detalle FOR
            SELECT D.ID_FACTURA_PROV_DETALLE, D.ID_FACTURA_PROVEEDOR, D.ID_ARTICULO, D.DESCRIPCION,
                   D.CANTIDAD, D.PRECIO_UNITARIO, D.ID_UNIDAD_MEDIDA, D.SUBTOTAL,
                   U.DESCRIPCION AS UNIDAD_MEDIDA
            FROM CP_FACTURA_PROVEEDOR_DETALLE D
            LEFT JOIN CP_TIPO_UNIDAD_MEDIDA U ON U.ID_UNIDAD_MEDIDA = D.ID_UNIDAD_MEDIDA
            WHERE D.ID_FACTURA_PROVEEDOR = p_id_factura
            ORDER BY D.ID_FACTURA_PROV_DETALLE ASC;
    END SP_OBTENER_FACTURA;

    PROCEDURE SP_LISTAR_PROVEEDORES(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_PROVEEDOR, NIT, RAZON_SOCIAL, NOMBRE_COMERCIAL, DIAS_CREDITO
            FROM PROVEEDOR
            WHERE ESTADO = 'A'
            ORDER BY RAZON_SOCIAL ASC;
    END SP_LISTAR_PROVEEDORES;

    PROCEDURE SP_INSERTAR_FACTURA(
        p_id_proveedor IN NUMBER,
        p_tipo_documento IN VARCHAR2,
        p_numero_dte IN VARCHAR2,
        p_serie_dte IN VARCHAR2,
        p_fecha_emision IN DATE,
        p_fecha_documento IN DATE,
        p_fecha_vencimiento IN DATE,
        p_id_factura_referencia IN NUMBER,
        p_id_factura_out OUT NUMBER
    ) IS
        L_ESTADO_INICIAL VARCHAR2(20);
    BEGIN
        VALIDAR_CABECERA(NULL, p_id_proveedor, p_tipo_documento, p_numero_dte, p_serie_dte,
                         p_fecha_emision, p_fecha_documento, p_fecha_vencimiento, p_id_factura_referencia);

        -- (ES_NOTA es BOOLEAN y no se puede usar dentro de la sentencia SQL)
        L_ESTADO_INICIAL := CASE WHEN ES_NOTA(p_tipo_documento) THEN 'APLICADA' ELSE 'PENDIENTE' END;

        INSERT INTO CP_FACTURA_PROVEEDOR (
            ID_PROVEEDOR, TIPO_DOCUMENTO, NUMERO_DTE, SERIE_DTE,
            FECHA_EMISION, FECHA_DOCUMENTO, FECHA_VENCIMIENTO, MONTO_TOTAL,
            MONTO_RETENCION_IVA, MONTO_RETENCION_ISR, SALDO_PENDIENTE, ESTADO, ID_FACTURA_REFERENCIA
        ) VALUES (
            p_id_proveedor, p_tipo_documento, TRIM(p_numero_dte), TRIM(p_serie_dte),
            p_fecha_emision, p_fecha_documento, p_fecha_vencimiento, 0,
            0, 0, 0, L_ESTADO_INICIAL,
            p_id_factura_referencia
        ) RETURNING ID_FACTURA_PROVEEDOR INTO p_id_factura_out;
    END SP_INSERTAR_FACTURA;

    PROCEDURE SP_VALIDAR_TIENE_DETALLE(p_id_factura IN NUMBER) IS
        L_N NUMBER;
    BEGIN
        SELECT COUNT(*) INTO L_N FROM CP_FACTURA_PROVEEDOR_DETALLE WHERE ID_FACTURA_PROVEEDOR = p_id_factura;
        IF L_N = 0 THEN
            RAISE_APPLICATION_ERROR(-20126, 'El documento debe tener al menos una linea de detalle.');
        END IF;
    END SP_VALIDAR_TIENE_DETALLE;

    PROCEDURE SP_ACTUALIZAR_FACTURA(
        p_id_factura IN NUMBER,
        p_id_proveedor IN NUMBER,
        p_numero_dte IN VARCHAR2,
        p_serie_dte IN VARCHAR2,
        p_fecha_emision IN DATE,
        p_fecha_documento IN DATE,
        p_fecha_vencimiento IN DATE,
        p_id_factura_referencia IN NUMBER
    ) IS
        L_F CP_FACTURA_PROVEEDOR%ROWTYPE;
    BEGIN
        LEER_FACTURA(p_id_factura, L_F);
        IF L_F.ESTADO = 'ANULADA' THEN
            RAISE_APPLICATION_ERROR(-20126, 'No se puede editar un documento ANULADO.');
        END IF;
        IF NOT ES_NOTA(L_F.TIPO_DOCUMENTO) THEN
            IF L_F.ESTADO != 'PENDIENTE' OR CONTRASENAS_ACTIVAS(p_id_factura) > 0 THEN
                RAISE_APPLICATION_ERROR(-20126,
                    'Solo se puede editar una factura PENDIENTE y sin contrasenas de pago (esta esta ' || L_F.ESTADO ||
                    '). Anule primero sus contrasenas.');
            END IF;
            IF p_id_proveedor != L_F.ID_PROVEEDOR AND NOTAS_ACTIVAS(p_id_factura) > 0 THEN
                RAISE_APPLICATION_ERROR(-20126,
                    'No se puede cambiar el proveedor: la factura tiene notas de credito/debito aplicadas.');
            END IF;
        END IF;

        VALIDAR_CABECERA(p_id_factura, p_id_proveedor, L_F.TIPO_DOCUMENTO, p_numero_dte, p_serie_dte,
                         p_fecha_emision, p_fecha_documento, p_fecha_vencimiento, p_id_factura_referencia);

        UPDATE CP_FACTURA_PROVEEDOR
        SET ID_PROVEEDOR = p_id_proveedor,
            NUMERO_DTE = TRIM(p_numero_dte),
            SERIE_DTE = TRIM(p_serie_dte),
            FECHA_EMISION = p_fecha_emision,
            FECHA_DOCUMENTO = p_fecha_documento,
            FECHA_VENCIMIENTO = p_fecha_vencimiento,
            ID_FACTURA_REFERENCIA = p_id_factura_referencia
        WHERE ID_FACTURA_PROVEEDOR = p_id_factura;

        -- Si una nota cambia de factura, se recalculan la anterior y la nueva.
        IF ES_NOTA(L_F.TIPO_DOCUMENTO) AND NVL(L_F.ID_FACTURA_REFERENCIA, -1) != NVL(p_id_factura_referencia, -1) THEN
            IF L_F.ID_FACTURA_REFERENCIA IS NOT NULL THEN
                SP_RECALCULAR(L_F.ID_FACTURA_REFERENCIA);
            END IF;
            SP_RECALCULAR(p_id_factura);
        END IF;
    END SP_ACTUALIZAR_FACTURA;

    PROCEDURE SP_ANULAR_FACTURA(p_id_factura IN NUMBER, p_motivo IN VARCHAR2) IS
        L_F CP_FACTURA_PROVEEDOR%ROWTYPE;
    BEGIN
        IF p_motivo IS NULL OR TRIM(p_motivo) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20129, 'El motivo de anulacion es obligatorio.');
        END IF;
        LEER_FACTURA(p_id_factura, L_F);
        IF L_F.ESTADO = 'ANULADA' THEN
            RAISE_APPLICATION_ERROR(-20129, 'El documento ' || p_id_factura || ' ya esta ANULADO.');
        END IF;
        IF NOT ES_NOTA(L_F.TIPO_DOCUMENTO) THEN
            IF CONTRASENAS_ACTIVAS(p_id_factura) > 0 THEN
                RAISE_APPLICATION_ERROR(-20129,
                    'La factura tiene contrasenas de pago activas; anulelas primero (las EMITIDAS, anulando su cheque).');
            END IF;
            IF NOTAS_ACTIVAS(p_id_factura) > 0 THEN
                RAISE_APPLICATION_ERROR(-20129,
                    'La factura tiene notas de credito/debito aplicadas; anulelas primero.');
            END IF;
        END IF;

        -- El motivo queda registrado en NOTAS.
        UPDATE CP_FACTURA_PROVEEDOR
        SET ESTADO = 'ANULADA',
            NOTAS = SUBSTR(TRIM(p_motivo), 1, 300)
        WHERE ID_FACTURA_PROVEEDOR = p_id_factura;

        -- Anular una nota revierte su efecto en la factura de referencia.
        IF ES_NOTA(L_F.TIPO_DOCUMENTO) AND L_F.ID_FACTURA_REFERENCIA IS NOT NULL THEN
            SP_RECALCULAR(L_F.ID_FACTURA_REFERENCIA);
        END IF;
    END SP_ANULAR_FACTURA;

    PROCEDURE SP_VALIDAR_DETALLE_EDITABLE(p_id_factura IN NUMBER) IS
        L_F CP_FACTURA_PROVEEDOR%ROWTYPE;
    BEGIN
        LEER_FACTURA(p_id_factura, L_F);
        IF L_F.ESTADO = 'ANULADA' THEN
            RAISE_APPLICATION_ERROR(-20130, 'No se puede modificar el detalle de un documento ANULADO.');
        END IF;
        IF NOT ES_NOTA(L_F.TIPO_DOCUMENTO) AND CONTRASENAS_ACTIVAS(p_id_factura) > 0 THEN
            RAISE_APPLICATION_ERROR(-20130,
                'No se puede modificar el detalle: la factura tiene contrasenas de pago activas.');
        END IF;
    END SP_VALIDAR_DETALLE_EDITABLE;

END PKG_CP_FACTURA_PROVEEDOR;
/

-- ---- PKG_CP_CONTRASENA_PAGO (backend/src/handlers/contrasenaPago.handler.ts) ----
-- Ciclo de vida de una contraseña de pago y su efecto en la factura:
--   PENDIENTE --(registrar cheque / registrar pago)--> EMITIDA / PAGADA
--   EMITIDA   --(cobrar cheque)--> PAGADA
--   EMITIDA   --(anular cheque)--> PENDIENTE (se repone el saldo)
--   PENDIENTE --(anular)--> ANULADA
-- El SALDO_PENDIENTE de la factura baja al EMITIR el pago (al salir de
-- PENDIENTE) y sube de nuevo si el cheque se anula: tras cada cambio de estado
-- se llama PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR (por eso va despues de ese
-- paquete). Va antes que PKG_CP_CHEQUE porque ese paquete llama a
-- SP_EMITIR_PAGO / SP_CONFIRMAR_PAGO / SP_REVERTIR_EMISION.
-- Codigos de error de negocio (ORA-201xx); el backend los devuelve como 400.
CREATE OR REPLACE PACKAGE PKG_CP_CONTRASENA_PAGO AS
    PROCEDURE SP_LISTAR_CONTRASENAS(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_OBTENER_CONTRASENA(p_id_contrasena IN NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_INSERTAR_CONTRASENA(
        p_id_factura_proveedor IN NUMBER,
        p_fecha IN DATE,
        p_forma_pago IN VARCHAR2,
        p_monto IN NUMBER,
        p_id_empleado_autoriza IN NUMBER,
        p_id_contrasena_out OUT NUMBER
    );
    PROCEDURE SP_ACTUALIZAR_CONTRASENA(
        p_id_contrasena IN NUMBER,
        p_forma_pago IN VARCHAR2,
        p_monto IN NUMBER,
        p_id_empleado_autoriza IN NUMBER
    );
    -- Requiere un motivo escrito; se guarda en NOTAS.
    PROCEDURE SP_ANULAR_CONTRASENA(p_id_contrasena IN NUMBER, p_motivo IN VARCHAR2);
    -- Pago directo (TRANSFERENCIA / EFECTIVO): PENDIENTE -> PAGADA y baja el saldo.
    PROCEDURE SP_REGISTRAR_PAGO(p_id_contrasena IN NUMBER);
    -- Usados por PKG_CP_CHEQUE:
    PROCEDURE SP_EMITIR_PAGO(p_id_contrasena IN NUMBER);
    PROCEDURE SP_CONFIRMAR_PAGO(p_id_contrasena IN NUMBER);
    PROCEDURE SP_REVERTIR_EMISION(p_id_contrasena IN NUMBER);
END PKG_CP_CONTRASENA_PAGO;
/

CREATE OR REPLACE PACKAGE BODY PKG_CP_CONTRASENA_PAGO AS

    -- Lee y BLOQUEA la contraseña (evita que dos usuarios la muevan a la vez).
    PROCEDURE LEER_CONTRASENA(
        p_id_contrasena IN NUMBER,
        p_row OUT CP_CONTRASENA_PAGO%ROWTYPE
    ) IS
    BEGIN
        SELECT * INTO p_row FROM CP_CONTRASENA_PAGO
        WHERE ID_CONTRASENA = p_id_contrasena
        FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20106, 'La contrasena de pago ' || p_id_contrasena || ' no existe.');
    END LEER_CONTRASENA;

    -- Lee y BLOQUEA la factura, validando que exista.
    PROCEDURE LEER_FACTURA(
        p_id_factura IN NUMBER,
        p_row OUT CP_FACTURA_PROVEEDOR%ROWTYPE
    ) IS
    BEGIN
        SELECT * INTO p_row FROM CP_FACTURA_PROVEEDOR
        WHERE ID_FACTURA_PROVEEDOR = p_id_factura
        FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20101, 'La factura ' || p_id_factura || ' no existe.');
    END LEER_FACTURA;

    -- Valida monto > 0 y que no exceda lo disponible de la factura:
    -- disponible = SALDO_PENDIENTE - montos de otras contraseñas PENDIENTES
    -- (las EMITIDAS/PAGADAS ya estan descontadas del saldo).
    PROCEDURE VALIDAR_MONTO(
        p_factura IN CP_FACTURA_PROVEEDOR%ROWTYPE,
        p_monto IN NUMBER,
        p_excluir_contrasena IN NUMBER
    ) IS
        L_COMPROMETIDO NUMBER;
        L_DISPONIBLE NUMBER;
    BEGIN
        IF p_monto IS NULL OR p_monto <= 0 THEN
            RAISE_APPLICATION_ERROR(-20103, 'El monto debe ser mayor a cero.');
        END IF;

        SELECT NVL(SUM(MONTO), 0) INTO L_COMPROMETIDO
        FROM CP_CONTRASENA_PAGO
        WHERE ID_FACTURA_PROVEEDOR = p_factura.ID_FACTURA_PROVEEDOR
          AND ESTADO = 'PENDIENTE'
          AND ID_CONTRASENA != NVL(p_excluir_contrasena, -1);

        L_DISPONIBLE := p_factura.SALDO_PENDIENTE - L_COMPROMETIDO;
        IF p_monto > L_DISPONIBLE THEN
            RAISE_APPLICATION_ERROR(-20104,
                'El monto (Q' || TO_CHAR(p_monto, 'FM999,999,990.00') ||
                ') excede lo disponible de la factura (Q' || TO_CHAR(GREATEST(L_DISPONIBLE, 0), 'FM999,999,990.00') ||
                '). Saldo pendiente: Q' || TO_CHAR(p_factura.SALDO_PENDIENTE, 'FM999,999,990.00') ||
                ', comprometido en otras contrasenas pendientes: Q' || TO_CHAR(L_COMPROMETIDO, 'FM999,999,990.00') || '.');
        END IF;
    END VALIDAR_MONTO;

    PROCEDURE VALIDAR_EMPLEADO(p_id_empleado IN NUMBER) IS
        L_EXISTE NUMBER;
    BEGIN
        IF p_id_empleado IS NULL THEN
            RETURN;
        END IF;
        SELECT COUNT(*) INTO L_EXISTE FROM NOM_EMPLEADO
        WHERE ID_EMPLEADO = p_id_empleado AND ESTADO = 'A' AND ELIMINADO = 'N';
        IF L_EXISTE = 0 THEN
            RAISE_APPLICATION_ERROR(-20105, 'El empleado que autoriza (' || p_id_empleado || ') no existe o no esta activo.');
        END IF;
    END VALIDAR_EMPLEADO;

    -- Valida que la factura admita un pago de p_monto (antes de cambiar el estado).
    -- El saldo y el estado de la factura los calcula PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR.
    PROCEDURE VALIDAR_PAGO(p_id_factura IN NUMBER, p_monto IN NUMBER) IS
        L_FACTURA CP_FACTURA_PROVEEDOR%ROWTYPE;
    BEGIN
        LEER_FACTURA(p_id_factura, L_FACTURA);
        IF L_FACTURA.ESTADO = 'ANULADA' THEN
            RAISE_APPLICATION_ERROR(-20102, 'La factura ' || p_id_factura || ' esta ANULADA; no admite pagos.');
        END IF;
        IF p_monto > L_FACTURA.SALDO_PENDIENTE THEN
            RAISE_APPLICATION_ERROR(-20104,
                'El pago (Q' || TO_CHAR(p_monto, 'FM999,999,990.00') ||
                ') excede el saldo pendiente de la factura (Q' || TO_CHAR(L_FACTURA.SALDO_PENDIENTE, 'FM999,999,990.00') || ').');
        END IF;
    END VALIDAR_PAGO;

    PROCEDURE SP_LISTAR_CONTRASENAS(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_CONTRASENA, ID_FACTURA_PROVEEDOR, FECHA, FORMA_PAGO, ESTADO, MONTO, ID_EMPLEADO_AUTORIZA, NOTAS
            FROM CP_CONTRASENA_PAGO
            ORDER BY ID_CONTRASENA DESC;
    END SP_LISTAR_CONTRASENAS;

    PROCEDURE SP_OBTENER_CONTRASENA(p_id_contrasena IN NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_CONTRASENA, ID_FACTURA_PROVEEDOR, FECHA, FORMA_PAGO, ESTADO, MONTO, ID_EMPLEADO_AUTORIZA, NOTAS
            FROM CP_CONTRASENA_PAGO
            WHERE ID_CONTRASENA = p_id_contrasena;
    END SP_OBTENER_CONTRASENA;

    PROCEDURE SP_INSERTAR_CONTRASENA(
        p_id_factura_proveedor IN NUMBER,
        p_fecha IN DATE,
        p_forma_pago IN VARCHAR2,
        p_monto IN NUMBER,
        p_id_empleado_autoriza IN NUMBER,
        p_id_contrasena_out OUT NUMBER
    ) IS
        L_FACTURA CP_FACTURA_PROVEEDOR%ROWTYPE;
    BEGIN
        LEER_FACTURA(p_id_factura_proveedor, L_FACTURA);
        IF L_FACTURA.TIPO_DOCUMENTO NOT IN ('FACTURA', 'FACTURA_ESPECIAL') THEN
            RAISE_APPLICATION_ERROR(-20113,
                'Las notas de credito y debito no se pagan: se aplican a su factura. Genere la contrasena sobre la factura.');
        END IF;
        IF L_FACTURA.ESTADO NOT IN ('PENDIENTE', 'PAGADA_PARCIAL') THEN
            RAISE_APPLICATION_ERROR(-20102,
                'La factura ' || p_id_factura_proveedor || ' esta ' || L_FACTURA.ESTADO || '; solo se generan contrasenas para facturas PENDIENTES o PAGADAS PARCIALMENTE.');
        END IF;
        VALIDAR_MONTO(L_FACTURA, p_monto, NULL);
        VALIDAR_EMPLEADO(p_id_empleado_autoriza);

        INSERT INTO CP_CONTRASENA_PAGO (ID_FACTURA_PROVEEDOR, FECHA, FORMA_PAGO, ESTADO, MONTO, ID_EMPLEADO_AUTORIZA)
        VALUES (p_id_factura_proveedor, p_fecha, p_forma_pago, 'PENDIENTE', p_monto, p_id_empleado_autoriza)
        RETURNING ID_CONTRASENA INTO p_id_contrasena_out;
    END SP_INSERTAR_CONTRASENA;

    PROCEDURE SP_ACTUALIZAR_CONTRASENA(
        p_id_contrasena IN NUMBER,
        p_forma_pago IN VARCHAR2,
        p_monto IN NUMBER,
        p_id_empleado_autoriza IN NUMBER
    ) IS
        L_CONTRASENA CP_CONTRASENA_PAGO%ROWTYPE;
        L_FACTURA CP_FACTURA_PROVEEDOR%ROWTYPE;
    BEGIN
        LEER_CONTRASENA(p_id_contrasena, L_CONTRASENA);
        IF L_CONTRASENA.ESTADO != 'PENDIENTE' THEN
            RAISE_APPLICATION_ERROR(-20107,
                'Solo se puede editar una contrasena PENDIENTE (esta esta ' || L_CONTRASENA.ESTADO || ').');
        END IF;
        LEER_FACTURA(L_CONTRASENA.ID_FACTURA_PROVEEDOR, L_FACTURA);
        VALIDAR_MONTO(L_FACTURA, p_monto, p_id_contrasena);
        VALIDAR_EMPLEADO(p_id_empleado_autoriza);

        UPDATE CP_CONTRASENA_PAGO
        SET FORMA_PAGO = p_forma_pago, MONTO = p_monto, ID_EMPLEADO_AUTORIZA = p_id_empleado_autoriza
        WHERE ID_CONTRASENA = p_id_contrasena;
    END SP_ACTUALIZAR_CONTRASENA;

    PROCEDURE SP_ANULAR_CONTRASENA(p_id_contrasena IN NUMBER, p_motivo IN VARCHAR2) IS
        L_CONTRASENA CP_CONTRASENA_PAGO%ROWTYPE;
        L_CHEQUES_ACTIVOS NUMBER;
    BEGIN
        IF p_motivo IS NULL OR TRIM(p_motivo) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20114, 'El motivo de anulacion es obligatorio.');
        END IF;
        LEER_CONTRASENA(p_id_contrasena, L_CONTRASENA);
        IF L_CONTRASENA.ESTADO = 'EMITIDA' THEN
            RAISE_APPLICATION_ERROR(-20108,
                'La contrasena tiene un pago EMITIDO; anule primero el cheque para devolverla a PENDIENTE.');
        ELSIF L_CONTRASENA.ESTADO != 'PENDIENTE' THEN
            RAISE_APPLICATION_ERROR(-20108,
                'Solo se puede anular una contrasena PENDIENTE (esta esta ' || L_CONTRASENA.ESTADO || ').');
        END IF;

        SELECT COUNT(*) INTO L_CHEQUES_ACTIVOS FROM CP_CHEQUE
        WHERE ID_CONTRASENA_PAGO = p_id_contrasena AND ESTADO IN ('EMITIDO', 'COBRADO');
        IF L_CHEQUES_ACTIVOS > 0 THEN
            RAISE_APPLICATION_ERROR(-20108,
                'La contrasena tiene cheques EMITIDOS o COBRADOS; anule primero esos cheques.');
        END IF;

        -- PENDIENTE aun no desconto saldo de la factura: no hay nada que reponer.
        -- El motivo queda registrado en NOTAS.
        UPDATE CP_CONTRASENA_PAGO
        SET ESTADO = 'ANULADA',
            NOTAS = SUBSTR(TRIM(p_motivo), 1, 300)
        WHERE ID_CONTRASENA = p_id_contrasena;
    END SP_ANULAR_CONTRASENA;

    PROCEDURE SP_REGISTRAR_PAGO(p_id_contrasena IN NUMBER) IS
        L_CONTRASENA CP_CONTRASENA_PAGO%ROWTYPE;
    BEGIN
        LEER_CONTRASENA(p_id_contrasena, L_CONTRASENA);
        IF L_CONTRASENA.FORMA_PAGO = 'CHEQUE' THEN
            RAISE_APPLICATION_ERROR(-20109,
                'La forma de pago es CHEQUE: registre el cheque en la vista de Cheques y cobrelo alli.');
        END IF;
        IF L_CONTRASENA.ESTADO != 'PENDIENTE' THEN
            RAISE_APPLICATION_ERROR(-20110,
                'Solo se puede registrar el pago de una contrasena PENDIENTE (esta esta ' || L_CONTRASENA.ESTADO || ').');
        END IF;

        VALIDAR_PAGO(L_CONTRASENA.ID_FACTURA_PROVEEDOR, L_CONTRASENA.MONTO);
        UPDATE CP_CONTRASENA_PAGO SET ESTADO = 'PAGADA' WHERE ID_CONTRASENA = p_id_contrasena;
        PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(L_CONTRASENA.ID_FACTURA_PROVEEDOR);
    END SP_REGISTRAR_PAGO;

    PROCEDURE SP_EMITIR_PAGO(p_id_contrasena IN NUMBER) IS
        L_CONTRASENA CP_CONTRASENA_PAGO%ROWTYPE;
    BEGIN
        LEER_CONTRASENA(p_id_contrasena, L_CONTRASENA);
        IF L_CONTRASENA.FORMA_PAGO != 'CHEQUE' THEN
            RAISE_APPLICATION_ERROR(-20111,
                'La contrasena ' || p_id_contrasena || ' es de forma de pago ' || L_CONTRASENA.FORMA_PAGO || '; no admite cheque.');
        END IF;
        IF L_CONTRASENA.ESTADO != 'PENDIENTE' THEN
            RAISE_APPLICATION_ERROR(-20112,
                'Solo se puede emitir cheque para una contrasena PENDIENTE (esta esta ' || L_CONTRASENA.ESTADO || ').');
        END IF;

        VALIDAR_PAGO(L_CONTRASENA.ID_FACTURA_PROVEEDOR, L_CONTRASENA.MONTO);
        UPDATE CP_CONTRASENA_PAGO SET ESTADO = 'EMITIDA' WHERE ID_CONTRASENA = p_id_contrasena;
        PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(L_CONTRASENA.ID_FACTURA_PROVEEDOR);
    END SP_EMITIR_PAGO;

    PROCEDURE SP_CONFIRMAR_PAGO(p_id_contrasena IN NUMBER) IS
        L_CONTRASENA CP_CONTRASENA_PAGO%ROWTYPE;
    BEGIN
        LEER_CONTRASENA(p_id_contrasena, L_CONTRASENA);
        IF L_CONTRASENA.ESTADO = 'EMITIDA' THEN
            UPDATE CP_CONTRASENA_PAGO SET ESTADO = 'PAGADA' WHERE ID_CONTRASENA = p_id_contrasena;
        ELSIF L_CONTRASENA.ESTADO = 'PENDIENTE' THEN
            -- Dato heredado (cheque emitido antes de estas reglas): el saldo aun no se desconto.
            VALIDAR_PAGO(L_CONTRASENA.ID_FACTURA_PROVEEDOR, L_CONTRASENA.MONTO);
            UPDATE CP_CONTRASENA_PAGO SET ESTADO = 'PAGADA' WHERE ID_CONTRASENA = p_id_contrasena;
            PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(L_CONTRASENA.ID_FACTURA_PROVEEDOR);
        ELSIF L_CONTRASENA.ESTADO = 'ANULADA' THEN
            RAISE_APPLICATION_ERROR(-20110, 'La contrasena ' || p_id_contrasena || ' esta ANULADA; no se puede confirmar su pago.');
        END IF;
        -- PAGADA: ya estaba confirmada, no hay cambios.
    END SP_CONFIRMAR_PAGO;

    PROCEDURE SP_REVERTIR_EMISION(p_id_contrasena IN NUMBER) IS
        L_CONTRASENA CP_CONTRASENA_PAGO%ROWTYPE;
    BEGIN
        LEER_CONTRASENA(p_id_contrasena, L_CONTRASENA);
        -- Solo una EMITIDA desconto saldo por el cheque; en otro estado no se toca.
        IF L_CONTRASENA.ESTADO = 'EMITIDA' THEN
            UPDATE CP_CONTRASENA_PAGO SET ESTADO = 'PENDIENTE' WHERE ID_CONTRASENA = p_id_contrasena;
            PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(L_CONTRASENA.ID_FACTURA_PROVEEDOR);
        END IF;
    END SP_REVERTIR_EMISION;

END PKG_CP_CONTRASENA_PAGO;
/

-- ---- PKG_CP_CHEQUE (backend/src/handlers/cheque.handler.ts) ----
-- Emitir, cobrar y anular un cheque mueven tambien su contrasena de pago
-- (y el saldo de la factura) via PKG_CP_CONTRASENA_PAGO.
CREATE OR REPLACE PACKAGE PKG_CP_CHEQUE AS
    PROCEDURE SP_LISTAR_CHEQUES(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_OBTENER_CHEQUE(p_id_cheque IN NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_INSERTAR_CHEQUE(
        p_id_contrasena_pago IN NUMBER,
        p_banco IN VARCHAR2,
        p_numero_cheque IN VARCHAR2,
        p_fecha_emision IN DATE,
        p_id_cheque_out OUT NUMBER
    );
    PROCEDURE SP_ACTUALIZAR_CHEQUE(
        p_id_cheque IN NUMBER,
        p_banco IN VARCHAR2,
        p_numero_cheque IN VARCHAR2,
        p_fecha_emision IN DATE
    );
    PROCEDURE SP_COBRAR_CHEQUE(
        p_id_cheque IN NUMBER,
        p_fecha_cobro IN DATE
    );
    PROCEDURE SP_ANULAR_CHEQUE(p_id_cheque IN NUMBER);
END PKG_CP_CHEQUE;
/

CREATE OR REPLACE PACKAGE BODY PKG_CP_CHEQUE AS

    PROCEDURE SP_LISTAR_CHEQUES(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_CHEQUE, ID_CONTRASENA_PAGO, BANCO, NUMERO_CHEQUE, FECHA_EMISION, FECHA_COBRO, ESTADO
            FROM CP_CHEQUE
            ORDER BY ID_CHEQUE DESC;
    END SP_LISTAR_CHEQUES;

    PROCEDURE SP_OBTENER_CHEQUE(p_id_cheque IN NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_CHEQUE, ID_CONTRASENA_PAGO, BANCO, NUMERO_CHEQUE, FECHA_EMISION, FECHA_COBRO, ESTADO
            FROM CP_CHEQUE
            WHERE ID_CHEQUE = p_id_cheque;
    END SP_OBTENER_CHEQUE;

    PROCEDURE SP_INSERTAR_CHEQUE(
        p_id_contrasena_pago IN NUMBER,
        p_banco IN VARCHAR2,
        p_numero_cheque IN VARCHAR2,
        p_fecha_emision IN DATE,
        p_id_cheque_out OUT NUMBER
    ) IS
    BEGIN
        IF p_fecha_emision > TRUNC(SYSDATE) THEN
            RAISE_APPLICATION_ERROR(-20001, 'La fecha de emision no puede ser futura.');
        END IF;
        -- Valida que la contrasena sea CHEQUE y PENDIENTE, la pasa a EMITIDA
        -- y descuenta su monto del saldo de la factura.
        PKG_CP_CONTRASENA_PAGO.SP_EMITIR_PAGO(p_id_contrasena_pago);

        INSERT INTO CP_CHEQUE (ID_CONTRASENA_PAGO, BANCO, NUMERO_CHEQUE, FECHA_EMISION, ESTADO)
        VALUES (p_id_contrasena_pago, p_banco, p_numero_cheque, p_fecha_emision, 'EMITIDO')
        RETURNING ID_CHEQUE INTO p_id_cheque_out;
    END SP_INSERTAR_CHEQUE;

    PROCEDURE SP_ACTUALIZAR_CHEQUE(
        p_id_cheque IN NUMBER,
        p_banco IN VARCHAR2,
        p_numero_cheque IN VARCHAR2,
        p_fecha_emision IN DATE
    ) IS
        L_ESTADO VARCHAR2(20);
    BEGIN
        SELECT ESTADO INTO L_ESTADO FROM CP_CHEQUE WHERE ID_CHEQUE = p_id_cheque;
        IF L_ESTADO != 'EMITIDO' THEN
            RAISE_APPLICATION_ERROR(-20003, 'Solo se puede editar un cheque en estado EMITIDO.');
        END IF;
        UPDATE CP_CHEQUE
        SET BANCO = NVL(p_banco, BANCO),
            NUMERO_CHEQUE = NVL(p_numero_cheque, NUMERO_CHEQUE),
            FECHA_EMISION = NVL(p_fecha_emision, FECHA_EMISION)
        WHERE ID_CHEQUE = p_id_cheque;
    END SP_ACTUALIZAR_CHEQUE;

    PROCEDURE SP_COBRAR_CHEQUE(
        p_id_cheque IN NUMBER,
        p_fecha_cobro IN DATE
    ) IS
        L_ESTADO VARCHAR2(20);
        L_FECHA_EMISION DATE;
        L_ID_CONTRASENA NUMBER;
    BEGIN
        SELECT ESTADO, FECHA_EMISION, ID_CONTRASENA_PAGO INTO L_ESTADO, L_FECHA_EMISION, L_ID_CONTRASENA
        FROM CP_CHEQUE WHERE ID_CHEQUE = p_id_cheque;

        IF L_ESTADO != 'EMITIDO' THEN
            RAISE_APPLICATION_ERROR(-20002, 'Solo se puede cobrar un cheque en estado EMITIDO.');
        END IF;
        IF p_fecha_cobro < L_FECHA_EMISION THEN
            RAISE_APPLICATION_ERROR(-20004, 'La fecha de cobro no puede ser anterior a la fecha de emision.');
        END IF;

        UPDATE CP_CHEQUE
        SET ESTADO = 'COBRADO', FECHA_COBRO = p_fecha_cobro
        WHERE ID_CHEQUE = p_id_cheque;

        -- La contrasena pasa a PAGADA.
        PKG_CP_CONTRASENA_PAGO.SP_CONFIRMAR_PAGO(L_ID_CONTRASENA);
    END SP_COBRAR_CHEQUE;

    PROCEDURE SP_ANULAR_CHEQUE(p_id_cheque IN NUMBER) IS
        L_ESTADO VARCHAR2(20);
        L_ID_CONTRASENA NUMBER;
        L_OTROS_ACTIVOS NUMBER;
    BEGIN
        SELECT ESTADO, ID_CONTRASENA_PAGO INTO L_ESTADO, L_ID_CONTRASENA
        FROM CP_CHEQUE WHERE ID_CHEQUE = p_id_cheque;
        IF L_ESTADO != 'EMITIDO' THEN
            RAISE_APPLICATION_ERROR(-20002, 'Solo se puede anular un cheque en estado EMITIDO.');
        END IF;
        UPDATE CP_CHEQUE SET ESTADO = 'ANULADO' WHERE ID_CHEQUE = p_id_cheque;

        -- Si no le queda otro cheque activo, la contrasena vuelve a PENDIENTE
        -- y se repone el saldo de la factura.
        SELECT COUNT(*) INTO L_OTROS_ACTIVOS FROM CP_CHEQUE
        WHERE ID_CONTRASENA_PAGO = L_ID_CONTRASENA AND ESTADO IN ('EMITIDO', 'COBRADO');
        IF L_OTROS_ACTIVOS = 0 THEN
            PKG_CP_CONTRASENA_PAGO.SP_REVERTIR_EMISION(L_ID_CONTRASENA);
        END IF;
    END SP_ANULAR_CHEQUE;

END PKG_CP_CHEQUE;
/

-- ---- PKG_FACTURA_PROVEEDOR_DETALLE (backend/src/handlers/facturaProveedorDetalle.handler.ts) ----
-- Cada cambio en las lineas recalcula el total y el saldo de su documento
-- (PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR). No se puede modificar el detalle de
-- un documento ANULADO o de una factura con contrasenas de pago activas, ni
-- dejar un documento sin lineas. Codigos de error de negocio: ORA-2013x.
CREATE OR REPLACE PACKAGE PKG_FACTURA_PROVEEDOR_DETALLE AS
    TYPE T_CURSOR IS REF CURSOR;

    PROCEDURE SP_INSERTAR_DETALLE (
        P_ID_FACTURA_PROVEEDOR IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROVEEDOR%TYPE,
        P_ID_ARTICULO          IN CP_FACTURA_PROVEEDOR_DETALLE.ID_ARTICULO%TYPE,
        P_DESCRIPCION          IN CP_FACTURA_PROVEEDOR_DETALLE.DESCRIPCION%TYPE,
        P_CANTIDAD             IN CP_FACTURA_PROVEEDOR_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_UNITARIO      IN CP_FACTURA_PROVEEDOR_DETALLE.PRECIO_UNITARIO%TYPE,
        P_ID_UNIDAD_MEDIDA     IN CP_FACTURA_PROVEEDOR_DETALLE.ID_UNIDAD_MEDIDA%TYPE,
        P_ID_DETALLE_OUT       OUT CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE
    );

    PROCEDURE SP_LISTAR_DETALLE (
        P_ID_FACTURA_PROVEEDOR IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROVEEDOR%TYPE DEFAULT NULL,
        P_CURSOR OUT T_CURSOR
    );

    PROCEDURE SP_OBTENER_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE,
        P_CURSOR OUT T_CURSOR
    );

    PROCEDURE SP_ACTUALIZAR_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE,
        P_ID_ARTICULO             IN CP_FACTURA_PROVEEDOR_DETALLE.ID_ARTICULO%TYPE,
        P_DESCRIPCION             IN CP_FACTURA_PROVEEDOR_DETALLE.DESCRIPCION%TYPE,
        P_CANTIDAD                IN CP_FACTURA_PROVEEDOR_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_UNITARIO         IN CP_FACTURA_PROVEEDOR_DETALLE.PRECIO_UNITARIO%TYPE,
        P_ID_UNIDAD_MEDIDA        IN CP_FACTURA_PROVEEDOR_DETALLE.ID_UNIDAD_MEDIDA%TYPE
    );

    PROCEDURE SP_ELIMINAR_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE
    );
END PKG_FACTURA_PROVEEDOR_DETALLE;
/

CREATE OR REPLACE PACKAGE BODY PKG_FACTURA_PROVEEDOR_DETALLE AS

    PROCEDURE VALIDAR_LINEA(
        P_DESCRIPCION      IN VARCHAR2,
        P_CANTIDAD         IN NUMBER,
        P_PRECIO_UNITARIO  IN NUMBER,
        P_ID_UNIDAD_MEDIDA IN NUMBER
    ) IS
    BEGIN
        IF TRIM(P_DESCRIPCION) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20131, 'La descripcion de la linea es obligatoria.');
        END IF;
        IF P_CANTIDAD IS NULL OR P_CANTIDAD <= 0 THEN
            RAISE_APPLICATION_ERROR(-20131, 'La cantidad debe ser mayor a cero.');
        END IF;
        IF P_PRECIO_UNITARIO IS NULL OR P_PRECIO_UNITARIO <= 0 THEN
            RAISE_APPLICATION_ERROR(-20131, 'El precio unitario debe ser mayor a cero.');
        END IF;
        IF P_ID_UNIDAD_MEDIDA IS NULL THEN
            RAISE_APPLICATION_ERROR(-20131, 'La unidad de medida es obligatoria.');
        END IF;
    END VALIDAR_LINEA;

    -- Devuelve la factura duena de la linea, o error si la linea no existe.
    FUNCTION FACTURA_DE_LINEA(P_ID_DETALLE IN NUMBER) RETURN NUMBER IS
        L_ID NUMBER;
    BEGIN
        SELECT ID_FACTURA_PROVEEDOR INTO L_ID FROM CP_FACTURA_PROVEEDOR_DETALLE
        WHERE ID_FACTURA_PROV_DETALLE = P_ID_DETALLE;
        RETURN L_ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20132, 'La linea de detalle ' || P_ID_DETALLE || ' no existe.');
    END FACTURA_DE_LINEA;

    PROCEDURE SP_INSERTAR_DETALLE (
        P_ID_FACTURA_PROVEEDOR IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROVEEDOR%TYPE,
        P_ID_ARTICULO          IN CP_FACTURA_PROVEEDOR_DETALLE.ID_ARTICULO%TYPE,
        P_DESCRIPCION          IN CP_FACTURA_PROVEEDOR_DETALLE.DESCRIPCION%TYPE,
        P_CANTIDAD             IN CP_FACTURA_PROVEEDOR_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_UNITARIO      IN CP_FACTURA_PROVEEDOR_DETALLE.PRECIO_UNITARIO%TYPE,
        P_ID_UNIDAD_MEDIDA     IN CP_FACTURA_PROVEEDOR_DETALLE.ID_UNIDAD_MEDIDA%TYPE,
        P_ID_DETALLE_OUT       OUT CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE
    ) IS
    BEGIN
        PKG_CP_FACTURA_PROVEEDOR.SP_VALIDAR_DETALLE_EDITABLE(P_ID_FACTURA_PROVEEDOR);
        VALIDAR_LINEA(P_DESCRIPCION, P_CANTIDAD, P_PRECIO_UNITARIO, P_ID_UNIDAD_MEDIDA);

        INSERT INTO CP_FACTURA_PROVEEDOR_DETALLE
            (ID_FACTURA_PROVEEDOR, ID_ARTICULO, DESCRIPCION, CANTIDAD, PRECIO_UNITARIO, ID_UNIDAD_MEDIDA, SUBTOTAL)
        VALUES
            (P_ID_FACTURA_PROVEEDOR, P_ID_ARTICULO, TRIM(P_DESCRIPCION), P_CANTIDAD, P_PRECIO_UNITARIO, P_ID_UNIDAD_MEDIDA,
             ROUND(P_CANTIDAD * P_PRECIO_UNITARIO, 2))
        RETURNING ID_FACTURA_PROV_DETALLE INTO P_ID_DETALLE_OUT;

        PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(P_ID_FACTURA_PROVEEDOR);
    END SP_INSERTAR_DETALLE;

    PROCEDURE SP_LISTAR_DETALLE (
        P_ID_FACTURA_PROVEEDOR IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROVEEDOR%TYPE DEFAULT NULL,
        P_CURSOR OUT T_CURSOR
    ) IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT ID_FACTURA_PROV_DETALLE, ID_FACTURA_PROVEEDOR, ID_ARTICULO,
                   DESCRIPCION, CANTIDAD, PRECIO_UNITARIO, ID_UNIDAD_MEDIDA, SUBTOTAL
            FROM CP_FACTURA_PROVEEDOR_DETALLE
            WHERE P_ID_FACTURA_PROVEEDOR IS NULL OR ID_FACTURA_PROVEEDOR = P_ID_FACTURA_PROVEEDOR
            ORDER BY ID_FACTURA_PROV_DETALLE DESC;
    END SP_LISTAR_DETALLE;

    PROCEDURE SP_OBTENER_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE,
        P_CURSOR OUT T_CURSOR
    ) IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT ID_FACTURA_PROV_DETALLE, ID_FACTURA_PROVEEDOR, ID_ARTICULO,
                   DESCRIPCION, CANTIDAD, PRECIO_UNITARIO, ID_UNIDAD_MEDIDA, SUBTOTAL
            FROM CP_FACTURA_PROVEEDOR_DETALLE
            WHERE ID_FACTURA_PROV_DETALLE = P_ID_FACTURA_PROV_DETALLE;
    END SP_OBTENER_DETALLE;

    PROCEDURE SP_ACTUALIZAR_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE,
        P_ID_ARTICULO             IN CP_FACTURA_PROVEEDOR_DETALLE.ID_ARTICULO%TYPE,
        P_DESCRIPCION             IN CP_FACTURA_PROVEEDOR_DETALLE.DESCRIPCION%TYPE,
        P_CANTIDAD                IN CP_FACTURA_PROVEEDOR_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_UNITARIO         IN CP_FACTURA_PROVEEDOR_DETALLE.PRECIO_UNITARIO%TYPE,
        P_ID_UNIDAD_MEDIDA        IN CP_FACTURA_PROVEEDOR_DETALLE.ID_UNIDAD_MEDIDA%TYPE
    ) IS
        L_ID_FACTURA NUMBER;
    BEGIN
        L_ID_FACTURA := FACTURA_DE_LINEA(P_ID_FACTURA_PROV_DETALLE);
        PKG_CP_FACTURA_PROVEEDOR.SP_VALIDAR_DETALLE_EDITABLE(L_ID_FACTURA);
        VALIDAR_LINEA(P_DESCRIPCION, P_CANTIDAD, P_PRECIO_UNITARIO, P_ID_UNIDAD_MEDIDA);

        UPDATE CP_FACTURA_PROVEEDOR_DETALLE
        SET ID_ARTICULO = P_ID_ARTICULO,
            DESCRIPCION = TRIM(P_DESCRIPCION),
            CANTIDAD = P_CANTIDAD,
            PRECIO_UNITARIO = P_PRECIO_UNITARIO,
            ID_UNIDAD_MEDIDA = P_ID_UNIDAD_MEDIDA,
            SUBTOTAL = ROUND(P_CANTIDAD * P_PRECIO_UNITARIO, 2)
        WHERE ID_FACTURA_PROV_DETALLE = P_ID_FACTURA_PROV_DETALLE;

        PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(L_ID_FACTURA);
    END SP_ACTUALIZAR_DETALLE;

    PROCEDURE SP_ELIMINAR_DETALLE (
        P_ID_FACTURA_PROV_DETALLE IN CP_FACTURA_PROVEEDOR_DETALLE.ID_FACTURA_PROV_DETALLE%TYPE
    ) IS
        L_ID_FACTURA NUMBER;
        L_LINEAS NUMBER;
    BEGIN
        L_ID_FACTURA := FACTURA_DE_LINEA(P_ID_FACTURA_PROV_DETALLE);
        PKG_CP_FACTURA_PROVEEDOR.SP_VALIDAR_DETALLE_EDITABLE(L_ID_FACTURA);

        SELECT COUNT(*) INTO L_LINEAS FROM CP_FACTURA_PROVEEDOR_DETALLE WHERE ID_FACTURA_PROVEEDOR = L_ID_FACTURA;
        IF L_LINEAS <= 1 THEN
            RAISE_APPLICATION_ERROR(-20133, 'No se puede eliminar la ultima linea: el documento debe tener al menos una.');
        END IF;

        DELETE FROM CP_FACTURA_PROVEEDOR_DETALLE WHERE ID_FACTURA_PROV_DETALLE = P_ID_FACTURA_PROV_DETALLE;

        PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(L_ID_FACTURA);
    END SP_ELIMINAR_DETALLE;
END PKG_FACTURA_PROVEEDOR_DETALLE;
/

-- ---- PKG_CP_RETENCION (backend/src/handlers/retencionHandler.ts) ----
-- CP_RETENCION es la fuente de las retenciones: cada alta, cambio o baja
-- recalcula MONTO_RETENCION_IVA / ISR y el saldo de la factura
-- (saldo = total - retenciones - NC + ND - pagos). Codigos de error: ORA-2014x.
CREATE OR REPLACE PACKAGE PKG_CP_RETENCION AS
    PROCEDURE SP_GET_ALL (p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_GET_BY_ID (p_id_retencion IN NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_INSERT (
        p_id_factura_proveedor IN NUMBER,
        p_tipo_retencion IN VARCHAR2,
        p_base_imponible IN NUMBER,
        p_porcentaje IN NUMBER,
        p_monto IN NUMBER,
        p_numero_constancia IN VARCHAR2,
        p_id_out OUT NUMBER
    );
    PROCEDURE SP_UPDATE (
        p_id_retencion IN NUMBER,
        p_id_factura_proveedor IN NUMBER,
        p_tipo_retencion IN VARCHAR2,
        p_base_imponible IN NUMBER,
        p_porcentaje IN NUMBER,
        p_monto IN NUMBER,
        p_numero_constancia IN VARCHAR2
    );
    PROCEDURE SP_DELETE (p_id_retencion IN NUMBER);
END PKG_CP_RETENCION;
/

CREATE OR REPLACE PACKAGE BODY PKG_CP_RETENCION AS

    PROCEDURE VALIDAR(p_id_factura IN NUMBER, p_monto IN NUMBER) IS
        L_TIPO VARCHAR2(20);
        L_ESTADO VARCHAR2(20);
    BEGIN
        BEGIN
            SELECT TIPO_DOCUMENTO, ESTADO INTO L_TIPO, L_ESTADO
            FROM CP_FACTURA_PROVEEDOR WHERE ID_FACTURA_PROVEEDOR = p_id_factura;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20140, 'La factura ' || p_id_factura || ' no existe.');
        END;
        IF L_TIPO NOT IN ('FACTURA', 'FACTURA_ESPECIAL') THEN
            RAISE_APPLICATION_ERROR(-20140, 'Las retenciones solo aplican a FACTURA o FACTURA ESPECIAL.');
        END IF;
        IF L_ESTADO = 'ANULADA' THEN
            RAISE_APPLICATION_ERROR(-20140, 'La factura ' || p_id_factura || ' esta ANULADA.');
        END IF;
        IF p_monto IS NULL OR p_monto <= 0 THEN
            RAISE_APPLICATION_ERROR(-20141, 'El monto de la retencion debe ser mayor a cero.');
        END IF;
    END VALIDAR;

    PROCEDURE SP_GET_ALL (p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_RETENCION, ID_FACTURA_PROVEEDOR, TIPO_RETENCION, BASE_IMPONIBLE,
                   PORCENTAJE, MONTO, NUMERO_CONSTANCIA
            FROM CP_RETENCION
            ORDER BY ID_RETENCION DESC;
    END SP_GET_ALL;

    PROCEDURE SP_GET_BY_ID (p_id_retencion IN NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_RETENCION, ID_FACTURA_PROVEEDOR, TIPO_RETENCION, BASE_IMPONIBLE,
                   PORCENTAJE, MONTO, NUMERO_CONSTANCIA
            FROM CP_RETENCION
            WHERE ID_RETENCION = p_id_retencion;
    END SP_GET_BY_ID;

    PROCEDURE SP_INSERT (
        p_id_factura_proveedor IN NUMBER,
        p_tipo_retencion IN VARCHAR2,
        p_base_imponible IN NUMBER,
        p_porcentaje IN NUMBER,
        p_monto IN NUMBER,
        p_numero_constancia IN VARCHAR2,
        p_id_out OUT NUMBER
    ) IS
    BEGIN
        VALIDAR(p_id_factura_proveedor, p_monto);
        INSERT INTO CP_RETENCION (
            ID_FACTURA_PROVEEDOR, TIPO_RETENCION, BASE_IMPONIBLE, PORCENTAJE, MONTO, NUMERO_CONSTANCIA
        ) VALUES (
            p_id_factura_proveedor, p_tipo_retencion, p_base_imponible, p_porcentaje, p_monto, p_numero_constancia
        ) RETURNING ID_RETENCION INTO p_id_out;

        PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(p_id_factura_proveedor);
    END SP_INSERT;

    PROCEDURE SP_UPDATE (
        p_id_retencion IN NUMBER,
        p_id_factura_proveedor IN NUMBER,
        p_tipo_retencion IN VARCHAR2,
        p_base_imponible IN NUMBER,
        p_porcentaje IN NUMBER,
        p_monto IN NUMBER,
        p_numero_constancia IN VARCHAR2
    ) IS
        L_FACTURA_ANTERIOR NUMBER;
    BEGIN
        BEGIN
            SELECT ID_FACTURA_PROVEEDOR INTO L_FACTURA_ANTERIOR FROM CP_RETENCION WHERE ID_RETENCION = p_id_retencion;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20142, 'La retencion ' || p_id_retencion || ' no existe.');
        END;
        VALIDAR(p_id_factura_proveedor, p_monto);

        UPDATE CP_RETENCION
        SET ID_FACTURA_PROVEEDOR = p_id_factura_proveedor,
            TIPO_RETENCION = p_tipo_retencion,
            BASE_IMPONIBLE = p_base_imponible,
            PORCENTAJE = p_porcentaje,
            MONTO = p_monto,
            NUMERO_CONSTANCIA = p_numero_constancia
        WHERE ID_RETENCION = p_id_retencion;

        PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(p_id_factura_proveedor);
        IF L_FACTURA_ANTERIOR != p_id_factura_proveedor THEN
            PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(L_FACTURA_ANTERIOR);
        END IF;
    END SP_UPDATE;

    PROCEDURE SP_DELETE (p_id_retencion IN NUMBER) IS
        L_FACTURA NUMBER;
    BEGIN
        BEGIN
            SELECT ID_FACTURA_PROVEEDOR INTO L_FACTURA FROM CP_RETENCION WHERE ID_RETENCION = p_id_retencion;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20142, 'La retencion ' || p_id_retencion || ' no existe.');
        END;
        DELETE FROM CP_RETENCION WHERE ID_RETENCION = p_id_retencion;
        PKG_CP_FACTURA_PROVEEDOR.SP_RECALCULAR(L_FACTURA);
    END SP_DELETE;
END PKG_CP_RETENCION;
/

-- ---- PKG_CP_UNIDAD_MEDIDA (backend/src/handlers/unidadMedidaHandler.ts) ----
CREATE OR REPLACE PACKAGE PKG_CP_UNIDAD_MEDIDA AS
    PROCEDURE SP_GET_ALL (p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_GET_BY_ID (p_id_unidad_medida IN NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_INSERT (p_descripcion IN VARCHAR2, p_id_out OUT NUMBER);
    PROCEDURE SP_UPDATE (p_id_unidad_medida IN NUMBER, p_descripcion IN VARCHAR2);
    PROCEDURE SP_DELETE (p_id_unidad_medida IN NUMBER);
END PKG_CP_UNIDAD_MEDIDA;
/

CREATE OR REPLACE PACKAGE BODY PKG_CP_UNIDAD_MEDIDA AS
    PROCEDURE SP_GET_ALL (p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_UNIDAD_MEDIDA, DESCRIPCION FROM CP_TIPO_UNIDAD_MEDIDA ORDER BY ID_UNIDAD_MEDIDA ASC;
    END SP_GET_ALL;

    PROCEDURE SP_GET_BY_ID (p_id_unidad_medida IN NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_UNIDAD_MEDIDA, DESCRIPCION FROM CP_TIPO_UNIDAD_MEDIDA WHERE ID_UNIDAD_MEDIDA = p_id_unidad_medida;
    END SP_GET_BY_ID;

    PROCEDURE SP_INSERT (p_descripcion IN VARCHAR2, p_id_out OUT NUMBER) IS
    BEGIN
        INSERT INTO CP_TIPO_UNIDAD_MEDIDA (DESCRIPCION) VALUES (p_descripcion)
        RETURNING ID_UNIDAD_MEDIDA INTO p_id_out;
    END SP_INSERT;

    PROCEDURE SP_UPDATE (p_id_unidad_medida IN NUMBER, p_descripcion IN VARCHAR2) IS
    BEGIN
        UPDATE CP_TIPO_UNIDAD_MEDIDA SET DESCRIPCION = p_descripcion WHERE ID_UNIDAD_MEDIDA = p_id_unidad_medida;
    END SP_UPDATE;

    PROCEDURE SP_DELETE (p_id_unidad_medida IN NUMBER) IS
    BEGIN
        DELETE FROM CP_TIPO_UNIDAD_MEDIDA WHERE ID_UNIDAD_MEDIDA = p_id_unidad_medida;
    END SP_DELETE;
END PKG_CP_UNIDAD_MEDIDA;
/

-- ---- CP_PKG_CAJA_CHICA_MOVIMIENTO (backend/src/handlers/cajaChicaMovimiento.handler.ts) ----
-- Ya funciona en produccion; se incluye igual para que el script sea completo.
CREATE OR REPLACE PACKAGE CP_PKG_CAJA_CHICA_MOVIMIENTO AS
    PROCEDURE INSERTAR (
        P_ID_CAJA_CHICA        IN  CP_CAJA_CHICA_MOVIMIENTO.ID_CAJA_CHICA%TYPE,
        P_TIPO_MOVIMIENTO      IN  CP_CAJA_CHICA_MOVIMIENTO.TIPO_MOVIMIENTO%TYPE,
        P_CONCEPTO             IN  CP_CAJA_CHICA_MOVIMIENTO.CONCEPTO%TYPE,
        P_MONTO                IN  CP_CAJA_CHICA_MOVIMIENTO.MONTO%TYPE,
        P_NUMERO_COMPROBANTE   IN  CP_CAJA_CHICA_MOVIMIENTO.NUMERO_COMPROBANTE%TYPE DEFAULT NULL,
        P_ID_MOVIMIENTO        OUT CP_CAJA_CHICA_MOVIMIENTO.ID_MOVIMIENTO_CAJA%TYPE
    );
    PROCEDURE ANULAR (
        P_ID_MOVIMIENTO_CAJA IN CP_CAJA_CHICA_MOVIMIENTO.ID_MOVIMIENTO_CAJA%TYPE,
        P_MOTIVO             IN VARCHAR2
    );
    PROCEDURE LISTAR (
        P_ID_CAJA_CHICA   IN  CP_CAJA_CHICA_MOVIMIENTO.ID_CAJA_CHICA%TYPE DEFAULT NULL,
        P_LIMITE          IN  NUMBER DEFAULT NULL,
        P_OFFSET          IN  NUMBER DEFAULT NULL,
        P_TOTAL_REGISTROS OUT NUMBER,
        P_CURSOR          OUT SYS_REFCURSOR
    );
    PROCEDURE LISTAR_TIPOS (P_CURSOR OUT SYS_REFCURSOR);
    FUNCTION OBTENER_SALDO (P_ID_CAJA_CHICA IN CP_CAJA_CHICA_MOVIMIENTO.ID_CAJA_CHICA%TYPE) RETURN NUMBER;
END CP_PKG_CAJA_CHICA_MOVIMIENTO;
/

CREATE OR REPLACE PACKAGE BODY CP_PKG_CAJA_CHICA_MOVIMIENTO AS

    FUNCTION TIPO_VALIDO (P_TIPO IN VARCHAR2) RETURN BOOLEAN IS
        L_TIPO VARCHAR2(20);
    BEGIN
        L_TIPO := UPPER(TRIM(P_TIPO));
        RETURN L_TIPO IN ('REPOSICION', 'GASTO', 'ANULADO');
    END TIPO_VALIDO;

    FUNCTION ES_EGRESO (P_TIPO IN VARCHAR2) RETURN BOOLEAN IS
        L_TIPO VARCHAR2(20);
    BEGIN
        L_TIPO := UPPER(TRIM(P_TIPO));
        RETURN L_TIPO = 'GASTO';
    END ES_EGRESO;

    FUNCTION OBTENER_SALDO (P_ID_CAJA_CHICA IN CP_CAJA_CHICA_MOVIMIENTO.ID_CAJA_CHICA%TYPE) RETURN NUMBER IS
        L_SALDO NUMBER(14, 2);
    BEGIN
        SELECT
            C.FONDO_ASIGNADO
            + NVL(SUM(CASE WHEN M.TIPO_MOVIMIENTO = 'REPOSICION' THEN M.MONTO ELSE 0 END), 0)
            - NVL(SUM(CASE WHEN M.TIPO_MOVIMIENTO = 'GASTO'      THEN M.MONTO ELSE 0 END), 0)
        INTO L_SALDO
        FROM CP_CAJA_CHICA C
        LEFT JOIN CP_CAJA_CHICA_MOVIMIENTO M ON M.ID_CAJA_CHICA = C.ID_CAJA_CHICA
        WHERE C.ID_CAJA_CHICA = P_ID_CAJA_CHICA
        GROUP BY C.FONDO_ASIGNADO;
        RETURN L_SALDO;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20010, 'La caja chica indicada no existe.');
    END OBTENER_SALDO;

    PROCEDURE INSERTAR (
        P_ID_CAJA_CHICA        IN  CP_CAJA_CHICA_MOVIMIENTO.ID_CAJA_CHICA%TYPE,
        P_TIPO_MOVIMIENTO      IN  CP_CAJA_CHICA_MOVIMIENTO.TIPO_MOVIMIENTO%TYPE,
        P_CONCEPTO             IN  CP_CAJA_CHICA_MOVIMIENTO.CONCEPTO%TYPE,
        P_MONTO                IN  CP_CAJA_CHICA_MOVIMIENTO.MONTO%TYPE,
        P_NUMERO_COMPROBANTE   IN  CP_CAJA_CHICA_MOVIMIENTO.NUMERO_COMPROBANTE%TYPE DEFAULT NULL,
        P_ID_MOVIMIENTO        OUT CP_CAJA_CHICA_MOVIMIENTO.ID_MOVIMIENTO_CAJA%TYPE
    ) IS
        L_TIPO  VARCHAR2(20);
        L_SALDO NUMBER(14, 2);
    BEGIN
        L_TIPO := UPPER(TRIM(P_TIPO_MOVIMIENTO));
        IF NOT TIPO_VALIDO(L_TIPO) THEN
            RAISE_APPLICATION_ERROR(-20001, 'Tipo de movimiento no válido: ' || L_TIPO);
        END IF;
        IF P_CONCEPTO IS NULL OR TRIM(P_CONCEPTO) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20002, 'El concepto del movimiento es obligatorio.');
        END IF;
        IF P_MONTO IS NULL OR P_MONTO <= 0 THEN
            RAISE_APPLICATION_ERROR(-20003, 'El monto debe ser mayor que cero.');
        END IF;
        L_SALDO := OBTENER_SALDO(P_ID_CAJA_CHICA);
        IF ES_EGRESO(L_TIPO) AND P_MONTO > L_SALDO THEN
            RAISE_APPLICATION_ERROR(-20004, 'Saldo insuficiente. Saldo disponible: Q ' || TO_CHAR(L_SALDO, 'FM999999990.00'));
        END IF;
        INSERT INTO CP_CAJA_CHICA_MOVIMIENTO (ID_CAJA_CHICA, FECHA, TIPO_MOVIMIENTO, CONCEPTO, MONTO, NUMERO_COMPROBANTE)
        VALUES (P_ID_CAJA_CHICA, SYSDATE, L_TIPO, TRIM(P_CONCEPTO), P_MONTO, TRIM(P_NUMERO_COMPROBANTE))
        RETURNING ID_MOVIMIENTO_CAJA INTO P_ID_MOVIMIENTO;
    END INSERTAR;

    PROCEDURE ANULAR (
        P_ID_MOVIMIENTO_CAJA IN CP_CAJA_CHICA_MOVIMIENTO.ID_MOVIMIENTO_CAJA%TYPE,
        P_MOTIVO             IN VARCHAR2
    ) IS
        L_TIPO_ACTUAL    VARCHAR2(20);
        L_CONCEPTO_ACTUAL VARCHAR2(300);
        L_MOTIVO_TRIM    VARCHAR2(200);
        L_CONCEPTO_NUEVO VARCHAR2(300);
    BEGIN
        IF P_ID_MOVIMIENTO_CAJA IS NULL THEN
            RAISE_APPLICATION_ERROR(-20005, 'El ID de movimiento es obligatorio.');
        END IF;
        IF P_MOTIVO IS NULL OR TRIM(P_MOTIVO) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20006, 'El motivo de anulación es obligatorio.');
        END IF;
        BEGIN
            SELECT TIPO_MOVIMIENTO, CONCEPTO
            INTO   L_TIPO_ACTUAL, L_CONCEPTO_ACTUAL
            FROM   CP_CAJA_CHICA_MOVIMIENTO
            WHERE  ID_MOVIMIENTO_CAJA = P_ID_MOVIMIENTO_CAJA;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20007, 'El movimiento indicado no existe.');
        END;
        IF UPPER(TRIM(L_TIPO_ACTUAL)) = 'ANULADO' THEN
            RAISE_APPLICATION_ERROR(-20008, 'El movimiento ya se encuentra anulado.');
        END IF;
        L_MOTIVO_TRIM    := SUBSTR(TRIM(P_MOTIVO), 1, 180);
        L_CONCEPTO_NUEVO := SUBSTR(TRIM(L_CONCEPTO_ACTUAL) || ' [ANULADO: ' || L_MOTIVO_TRIM || ']', 1, 300);
        UPDATE CP_CAJA_CHICA_MOVIMIENTO
        SET    TIPO_MOVIMIENTO = 'ANULADO', CONCEPTO = L_CONCEPTO_NUEVO
        WHERE  ID_MOVIMIENTO_CAJA = P_ID_MOVIMIENTO_CAJA;
    END ANULAR;

    PROCEDURE LISTAR (
        P_ID_CAJA_CHICA   IN  CP_CAJA_CHICA_MOVIMIENTO.ID_CAJA_CHICA%TYPE DEFAULT NULL,
        P_LIMITE          IN  NUMBER DEFAULT NULL,
        P_OFFSET          IN  NUMBER DEFAULT NULL,
        P_TOTAL_REGISTROS OUT NUMBER,
        P_CURSOR          OUT SYS_REFCURSOR
    ) IS
    BEGIN
        SELECT COUNT(*)
        INTO   P_TOTAL_REGISTROS
        FROM   CP_CAJA_CHICA_MOVIMIENTO M
        WHERE  (P_ID_CAJA_CHICA IS NULL OR M.ID_CAJA_CHICA = P_ID_CAJA_CHICA);

        OPEN P_CURSOR FOR
            SELECT
                M.ID_MOVIMIENTO_CAJA, M.ID_CAJA_CHICA, M.FECHA, M.TIPO_MOVIMIENTO,
                M.CONCEPTO, M.MONTO, M.NUMERO_COMPROBANTE,
                CP_PKG_CAJA_CHICA_MOVIMIENTO.OBTENER_SALDO(M.ID_CAJA_CHICA) AS SALDO_DISPONIBLE
            FROM CP_CAJA_CHICA_MOVIMIENTO M
            WHERE (P_ID_CAJA_CHICA IS NULL OR M.ID_CAJA_CHICA = P_ID_CAJA_CHICA)
            ORDER BY M.FECHA DESC, M.ID_MOVIMIENTO_CAJA DESC
            OFFSET NVL(P_OFFSET, 0) ROWS
            FETCH NEXT NVL(P_LIMITE, 1000000) ROWS ONLY;
    END LISTAR;

    PROCEDURE LISTAR_TIPOS (P_CURSOR OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT 'REPOSICION' AS CODIGO FROM DUAL
            UNION ALL
            SELECT 'GASTO' AS CODIGO FROM DUAL;
    END LISTAR_TIPOS;

END CP_PKG_CAJA_CHICA_MOVIMIENTO;
/

-- ---- PKG_CAJA_CHICA (backend/src/handlers/cajaChica.handler.ts) ----
-- CORREGIDO: la version original (database/CajaChica/PKG_CAJA_CHICA.sql)
-- apuntaba a CXP_CAJA_CHICA, tabla que nunca se creo -> ORA-04063 / 500 en
-- /api/cajas-chicas. Esta version apunta a CP_CAJA_CHICA (la tabla real,
-- la misma que ya usa CP_PKG_CAJA_CHICA_MOVIMIENTO).
CREATE OR REPLACE PACKAGE PKG_CAJA_CHICA AS
    PROCEDURE SP_LISTAR_CAJAS_CHICAS(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_OBTENER_CAJA_CHICA(p_id_caja_chica IN NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_INSERTAR_CAJA_CHICA(
        p_id_sucursal IN NUMBER,
        p_id_empleado_responsable IN NUMBER,
        p_fondo_asignado IN NUMBER,
        p_id_caja_chica_out OUT NUMBER
    );
    PROCEDURE SP_ACTUALIZAR_CAJA_CHICA(
        p_id_caja_chica IN NUMBER,
        p_id_empleado_responsable IN NUMBER,
        p_fondo_asignado IN NUMBER,
        p_estado IN VARCHAR2
    );
    PROCEDURE SP_INACTIVAR_CAJA_CHICA(
        p_id_caja_chica IN NUMBER,
        p_eliminado_por IN NUMBER DEFAULT NULL
    );
    PROCEDURE SP_LISTAR_SUCURSALES(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE SP_LISTAR_EMPLEADOS(p_cursor OUT SYS_REFCURSOR);
END PKG_CAJA_CHICA;
/

CREATE OR REPLACE PACKAGE BODY PKG_CAJA_CHICA AS

    PROCEDURE SP_LISTAR_CAJAS_CHICAS(p_cursor OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN p_cursor FOR
            SELECT
                c.ID_CAJA_CHICA, c.ID_SUCURSAL, s.NOMBRE AS SUCURSAL_NOMBRE, s.CODIGO AS SUCURSAL_CODIGO,
                c.ID_EMPLEADO_RESPONSABLE, (e.NOMBRES || ' ' || e.APELLIDOS) AS RESPONSABLE_NOMBRE,
                e.CODIGO_EMPLEADO AS RESPONSABLE_CODIGO, c.FONDO_ASIGNADO, c.ESTADO
            FROM CP_CAJA_CHICA c
            INNER JOIN NOM_SUCURSAL s ON c.ID_SUCURSAL = s.ID_SUCURSAL
            INNER JOIN NOM_EMPLEADO e ON c.ID_EMPLEADO_RESPONSABLE = e.ID_EMPLEADO
            WHERE c.ELIMINADO = 'N'
            ORDER BY c.ID_CAJA_CHICA DESC;
    END SP_LISTAR_CAJAS_CHICAS;

    PROCEDURE SP_OBTENER_CAJA_CHICA(p_id_caja_chica IN NUMBER, p_cursor OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN p_cursor FOR
            SELECT
                c.ID_CAJA_CHICA, c.ID_SUCURSAL, s.NOMBRE AS SUCURSAL_NOMBRE, s.CODIGO AS SUCURSAL_CODIGO,
                c.ID_EMPLEADO_RESPONSABLE, (e.NOMBRES || ' ' || e.APELLIDOS) AS RESPONSABLE_NOMBRE,
                e.CODIGO_EMPLEADO AS RESPONSABLE_CODIGO, c.FONDO_ASIGNADO, c.ESTADO
            FROM CP_CAJA_CHICA c
            INNER JOIN NOM_SUCURSAL s ON c.ID_SUCURSAL = s.ID_SUCURSAL
            INNER JOIN NOM_EMPLEADO e ON c.ID_EMPLEADO_RESPONSABLE = e.ID_EMPLEADO
            WHERE c.ID_CAJA_CHICA = p_id_caja_chica AND c.ELIMINADO = 'N';
    END SP_OBTENER_CAJA_CHICA;

    PROCEDURE SP_INSERTAR_CAJA_CHICA(
        p_id_sucursal IN NUMBER,
        p_id_empleado_responsable IN NUMBER,
        p_fondo_asignado IN NUMBER,
        p_id_caja_chica_out OUT NUMBER
    ) AS
    BEGIN
        INSERT INTO CP_CAJA_CHICA (ID_SUCURSAL, ID_EMPLEADO_RESPONSABLE, FONDO_ASIGNADO, ESTADO, ELIMINADO)
        VALUES (p_id_sucursal, p_id_empleado_responsable, p_fondo_asignado, 'A', 'N')
        RETURNING ID_CAJA_CHICA INTO p_id_caja_chica_out;
    END SP_INSERTAR_CAJA_CHICA;

    PROCEDURE SP_ACTUALIZAR_CAJA_CHICA(
        p_id_caja_chica IN NUMBER,
        p_id_empleado_responsable IN NUMBER,
        p_fondo_asignado IN NUMBER,
        p_estado IN VARCHAR2
    ) AS
    BEGIN
        UPDATE CP_CAJA_CHICA
        SET ID_EMPLEADO_RESPONSABLE = p_id_empleado_responsable,
            FONDO_ASIGNADO = p_fondo_asignado,
            ESTADO = NVL(p_estado, ESTADO)
        WHERE ID_CAJA_CHICA = p_id_caja_chica AND ELIMINADO = 'N';
    END SP_ACTUALIZAR_CAJA_CHICA;

    PROCEDURE SP_INACTIVAR_CAJA_CHICA(
        p_id_caja_chica IN NUMBER,
        p_eliminado_por IN NUMBER DEFAULT NULL
    ) AS
    BEGIN
        UPDATE CP_CAJA_CHICA
        SET ESTADO = 'I', ELIMINADO = 'S', FECHA_ELIMINACION = SYSTIMESTAMP,
            ELIMINADO_POR = NVL(p_eliminado_por, ELIMINADO_POR)
        WHERE ID_CAJA_CHICA = p_id_caja_chica;
    END SP_INACTIVAR_CAJA_CHICA;

    PROCEDURE SP_LISTAR_SUCURSALES(p_cursor OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_SUCURSAL, CODIGO, NOMBRE FROM NOM_SUCURSAL
            WHERE ESTADO = 'A' AND ELIMINADO = 'N'
            ORDER BY NOMBRE ASC;
    END SP_LISTAR_SUCURSALES;

    PROCEDURE SP_LISTAR_EMPLEADOS(p_cursor OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN p_cursor FOR
            SELECT ID_EMPLEADO, CODIGO_EMPLEADO, (NOMBRES || ' ' || APELLIDOS) AS NOMBRE_COMPLETO, ID_SUCURSAL
            FROM NOM_EMPLEADO
            WHERE ESTADO = 'A' AND ELIMINADO = 'N'
            ORDER BY NOMBRES ASC;
    END SP_LISTAR_EMPLEADOS;

END PKG_CAJA_CHICA;
/


-- ============================================================================
-- FIN de estructura y codigo. Este archivo NO inserta ningun dato, ni de
-- catalogo ni de prueba -- eso vive completo en database/RUN_ALL_SEEDS.sql
-- y los archivos que enlaza (uno por modulo). Correr en este orden:
--   1. Este archivo (00_MASTER_SETUP.sql)
--   2. database/RUN_ALL_SEEDS.sql
-- ============================================================================
