-- ============================================================================
-- DEPENDENCIAS EXTERNAS - ESTRUCTURA (tablas de OTROS modulos)
-- ============================================================================
-- Cuentas por Pagar NO es dueno de estas tablas, pero las necesita para
-- funcionar y para poder probar sus vistas. Mientras los modulos duenos
-- (Nomina, Compras, Inventarios) no entreguen sus scripts reales, este
-- archivo las crea con la MISMA definicion que se usa en el proyecto.
-- Ver README.md de esta carpeta (por que existe y como reemplazarlo).
--
--   Tabla                Modulo dueno   La usa en Cuentas por Pagar
--   -------------------  -------------  --------------------------------------
--   NOM_DEPARTAMENTO     Nomina         (requerida por NOM_EMPLEADO)
--   NOM_PUESTO           Nomina         (requerida por NOM_EMPLEADO)
--   NOM_SUCURSAL         Nomina         Caja Chica (sucursal de la caja)
--   NOM_EMPLEADO         Nomina         Caja Chica (responsable) y
--                                       Contrasenas de Pago (empleado que autoriza)
--   PROVEEDOR            Compras        Facturas Proveedor (proveedor del DTE)
--   CATEGORIA_ARTICULO   Inventarios    (requerida por ARTICULO)
--   ARTICULO             Inventarios    Lineas de factura (ID articulo, opcional)
--
-- PROVEEDOR, CATEGORIA_ARTICULO y ARTICULO tambien los crea SCRIPT_GENERAL.sql
-- (paso 0). Si ya existen, aqui no se tocan: cada CREATE TABLE ignora el error
-- "ya existe" (ORA-00955). No hay ningun DROP ni se borran filas.
--
-- ORDEN: correr ANTES de 00_MASTER_SETUP.sql (sus paquetes, vista y llaves
-- foraneas usan estas tablas). Ver database/Pasos.SQL.txt.
-- ============================================================================


-- ============================================================================
-- NOMINA: catalogos base (sucursal, puesto, departamento, empleado)
-- El prefijo NOM_ es el que usa el codigo de Cuentas por Pagar
-- (PKG_CAJA_CHICA, PKG_CP_CONTRASENA_PAGO y las llaves de CP_CAJA_CHICA).
-- ============================================================================

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE NOM_DEPARTAMENTO (
        ID_DEPARTAMENTO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NOMBRE VARCHAR2(100) NOT NULL,
        ID_GERENTE NUMBER,
        CONSTRAINT PK_NOM_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE NOM_PUESTO (
        ID_PUESTO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NOMBRE VARCHAR2(100) NOT NULL,
        ES_VENDEDOR CHAR(1) DEFAULT ''N'' CHECK (ES_VENDEDOR IN (''S'',''N'')),
        CONSTRAINT PK_NOM_PUESTO PRIMARY KEY (ID_PUESTO)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE NOM_SUCURSAL (
        ID_SUCURSAL NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        CODIGO VARCHAR2(10) NOT NULL UNIQUE,
        NOMBRE VARCHAR2(100) NOT NULL,
        TIPO VARCHAR2(20) NOT NULL CHECK (TIPO IN (''TIENDA'',''OFICINA_CENTRAL'',''BODEGA_CENTRAL'')),
        DIRECCION VARCHAR2(200),
        TELEFONO VARCHAR2(20),
        ESTADO CHAR(1) DEFAULT ''A'' CHECK (ESTADO IN (''A'',''I'')),
        ELIMINADO CHAR(1) DEFAULT ''N'' NOT NULL CHECK (ELIMINADO IN (''S'',''N'')),
        FECHA_ELIMINACION TIMESTAMP,
        ELIMINADO_POR NUMBER,
        CONSTRAINT PK_NOM_SUCURSAL PRIMARY KEY (ID_SUCURSAL)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE NOM_EMPLEADO (
        ID_EMPLEADO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        CODIGO_EMPLEADO VARCHAR2(15) NOT NULL UNIQUE,
        NOMBRES VARCHAR2(100) NOT NULL,
        APELLIDOS VARCHAR2(100) NOT NULL,
        DPI VARCHAR2(20) UNIQUE,
        NIT VARCHAR2(20),
        FECHA_NACIMIENTO DATE,
        FECHA_INGRESO DATE NOT NULL,
        FECHA_EGRESO DATE,
        ID_PUESTO NUMBER NOT NULL,
        ID_DEPARTAMENTO NUMBER,
        ID_SUCURSAL NUMBER NOT NULL,
        ID_JEFE_INMEDIATO NUMBER,
        TIPO_EMPLEADO VARCHAR2(20) NOT NULL CHECK (TIPO_EMPLEADO IN (''VENDEDOR'',''ADMINISTRATIVO'',''OFICINA_CENTRAL'',''COBRADOR'',''BODEGA'')),
        SALARIO_BASE NUMBER(12,2) NOT NULL,
        PORCENTAJE_COMISION NUMBER(6,5) DEFAULT 0.0005,
        TIENE_VEHICULO CHAR(1) DEFAULT ''N'' CHECK (TIENE_VEHICULO IN (''S'',''N'')),
        MONTO_DESCUENTO_PARQUEO NUMBER(8,2) DEFAULT 250.00,
        NO_AFILIACION_IGSS VARCHAR2(20),
        CUENTA_BANCARIA VARCHAR2(30),
        BANCO VARCHAR2(50),
        ESTADO CHAR(1) DEFAULT ''A'' CHECK (ESTADO IN (''A'',''I'')),
        ELIMINADO CHAR(1) DEFAULT ''N'' NOT NULL CHECK (ELIMINADO IN (''S'',''N'')),
        FECHA_ELIMINACION TIMESTAMP,
        ELIMINADO_POR NUMBER,
        CONSTRAINT PK_NOM_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE NOM_EMPLEADO ADD CONSTRAINT FK_NOM_EMPLEADO_PUESTO FOREIGN KEY (ID_PUESTO) REFERENCES NOM_PUESTO(ID_PUESTO)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE NOM_EMPLEADO ADD CONSTRAINT FK_NOM_EMPLEADO_DEPTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES NOM_DEPARTAMENTO(ID_DEPARTAMENTO)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE NOM_EMPLEADO ADD CONSTRAINT FK_NOM_EMPLEADO_SUC FOREIGN KEY (ID_SUCURSAL) REFERENCES NOM_SUCURSAL(ID_SUCURSAL)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ============================================================================
-- COMPRAS: catalogo de proveedores (misma definicion que SCRIPT_GENERAL.sql)
-- Lo usan PKG_CP_FACTURA_PROVEEDOR (valida el proveedor) y la vista
-- VW_CP_FACTURA_PROVEEDOR (razon social y NIT en Facturas Proveedor).
-- ============================================================================

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE PROVEEDOR (
        ID_PROVEEDOR NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NIT VARCHAR2(20) NOT NULL UNIQUE,
        RAZON_SOCIAL VARCHAR2(150) NOT NULL,
        NOMBRE_COMERCIAL VARCHAR2(150),
        DIRECCION VARCHAR2(200),
        TELEFONO VARCHAR2(20),
        EMAIL VARCHAR2(100),
        DIAS_CREDITO NUMBER(3) DEFAULT 0,
        CALIFICACION VARCHAR2(20),
        CUENTA_BANCARIA VARCHAR2(30),
        BANCO VARCHAR2(50),
        ESTADO CHAR(1) DEFAULT ''A'' CHECK (ESTADO IN (''A'',''I'')),
        CONSTRAINT PK_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/


-- ============================================================================
-- INVENTARIOS: catalogo de articulos (misma definicion que SCRIPT_GENERAL.sql)
-- ID_ARTICULO de las lineas de factura (CP_FACTURA_PROVEEDOR_DETALLE) apunta
-- aqui. Es opcional en la factura (hay lineas de servicios sin articulo).
-- ============================================================================

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE CATEGORIA_ARTICULO (
        ID_CATEGORIA NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NOMBRE VARCHAR2(100) NOT NULL,
        CONSTRAINT PK_CATEGORIA_ARTICULO PRIMARY KEY (ID_CATEGORIA)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE ARTICULO (
        ID_ARTICULO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        CODIGO VARCHAR2(20) NOT NULL UNIQUE,
        NOMBRE VARCHAR2(150) NOT NULL,
        DESCRIPCION VARCHAR2(500),
        ID_CATEGORIA NUMBER,
        UNIDAD_MEDIDA VARCHAR2(20) NOT NULL,
        TIPO_ARTICULO VARCHAR2(30) NOT NULL CHECK (TIPO_ARTICULO IN (''MERCADERIA_VENTA'',''ACTIVO_FIJO'',''MATERIAL_USO_INTERNO'',''TIENDA_INTERNA_EMPLEADOS'')),
        METODO_COSTEO VARCHAR2(10) DEFAULT ''FIFO'',
        COSTO_PROMEDIO NUMBER(14,4) DEFAULT 0,
        PRECIO_VENTA NUMBER(12,2) DEFAULT 0,
        STOCK_MINIMO NUMBER(12,2) DEFAULT 0,
        STOCK_MAXIMO NUMBER(12,2) DEFAULT 0,
        ESTADO CHAR(1) DEFAULT ''A'' CHECK (ESTADO IN (''A'',''I'')),
        CONSTRAINT PK_ARTICULO PRIMARY KEY (ID_ARTICULO)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Misma llave que SCRIPT_GENERAL.sql (FK_ARTICULO_1); si ya existe, no hace nada.
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ARTICULO ADD CONSTRAINT FK_ARTICULO_1 FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_ARTICULO(ID_CATEGORIA)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-2275, -2264) THEN RAISE; END IF;
END;
/

-- ============================================================================
-- FIN. Siguiente: 02_DATOS_DEPENDENCIAS.sql (o RUN_DEPENDENCIAS.sql para ambos).
-- ============================================================================
