-- ============================================================================
-- DEPENDENCIAS EXTERNAS - DATOS DE PRUEBA (de OTROS modulos)
-- ============================================================================
-- Datos minimos de Nomina, Compras e Inventarios para poder probar TODAS las
-- vistas de Cuentas por Pagar que dependen de ellos:
--   * Caja Chica .................. sucursales y empleados (responsable)
--   * Contrasenas de Pago ......... empleados (empleado que autoriza)
--   * Facturas Proveedor .......... proveedores (selector + validacion)
--   * Lineas de factura ........... articulos (ID articulo, opcional)
--
-- Son DATOS DE PRUEBA, no los reales: cuando Nomina / Compras / Inventarios
-- se integren, este archivo se deja de ejecutar y se usan los datos de ellos
-- (ver README.md de esta carpeta).
--
-- RE-EJECUTABLE: cada fila se inserta solo si no existe (por su codigo, NIT o
-- nombre). Correrlo dos veces no duplica nada.
-- Requiere: 01_SETUP_DEPENDENCIAS.sql ya ejecutado.
-- Los seeds de Cuentas por Pagar (RUN_ALL_SEEDS.sql) buscan estos registros
-- por su CODIGO / NIT, nunca por ID.
-- ============================================================================

SET DEFINE OFF

-- ----------------------------------------------------------------------------
-- NOMINA 1/4: Departamentos (los empleados de prueba usan 'Administración y Finanzas')
-- ----------------------------------------------------------------------------
INSERT INTO NOM_DEPARTAMENTO (NOMBRE)
SELECT 'Administración y Finanzas'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas');

INSERT INTO NOM_DEPARTAMENTO (NOMBRE)
SELECT 'Operaciones y Sucursales'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Operaciones y Sucursales');

INSERT INTO NOM_DEPARTAMENTO (NOMBRE)
SELECT 'Auditoría y Control Interno'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Auditoría y Control Interno');

INSERT INTO NOM_DEPARTAMENTO (NOMBRE)
SELECT 'Logística y Almacén'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Logística y Almacén');

-- ----------------------------------------------------------------------------
-- NOMINA 2/4: Puestos (los empleados de prueba usan 'Encargado de Tienda / Custodio')
-- ----------------------------------------------------------------------------
INSERT INTO NOM_PUESTO (NOMBRE, ES_VENDEDOR)
SELECT 'Encargado de Tienda / Custodio', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio');

INSERT INTO NOM_PUESTO (NOMBRE, ES_VENDEDOR)
SELECT 'Administrador de Sucursal', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_PUESTO WHERE NOMBRE = 'Administrador de Sucursal');

INSERT INTO NOM_PUESTO (NOMBRE, ES_VENDEDOR)
SELECT 'Gerente de Operaciones', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_PUESTO WHERE NOMBRE = 'Gerente de Operaciones');

INSERT INTO NOM_PUESTO (NOMBRE, ES_VENDEDOR)
SELECT 'Supervisor Regional', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_PUESTO WHERE NOMBRE = 'Supervisor Regional');

INSERT INTO NOM_PUESTO (NOMBRE, ES_VENDEDOR)
SELECT 'Auxiliar Administrativo', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_PUESTO WHERE NOMBRE = 'Auxiliar Administrativo');

-- ----------------------------------------------------------------------------
-- NOMINA 3/4: Sucursales SUC-001 a SUC-016 (Caja Chica: una caja por sucursal)
-- ----------------------------------------------------------------------------
INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-001', 'Tienda Central Zona 1', 'TIENDA', '6ta Avenida 4-15 Zona 1, Ciudad de Guatemala', '2234-5678', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-001');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-002', 'Sucursal Pradera Zona 10', 'TIENDA', 'Boulevard Los Próceres 24-69 Zona 10, C.C. Pradera', '2345-6789', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-002');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-003', 'Oficinas Centrales Reforma', 'OFICINA_CENTRAL', 'Avenida Reforma 12-01 Zona 9, Edificio Corporativo', '2456-7890', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-003');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-004', 'Miraflores Zona 11', 'TIENDA', '21 Avenida 4-32 Zona 11, C.C. Miraflores', '2471-1122', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-004');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-005', 'Oakland Mall Zona 10', 'TIENDA', 'Diagonal 6 13-01 Zona 10, C.C. Oakland Mall', '2363-3344', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-005');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-006', 'Portales Zona 17', 'TIENDA', 'Km 4.5 Carretera al Atlántico, C.C. Portales', '2256-5566', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-006');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-007', 'Pradera Concepción', 'TIENDA', 'Km 15.5 Carretera a El Salvador, Santa Catarina Pinula', '6634-7788', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-007');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-008', 'Naranjo Mall Mixco', 'TIENDA', '23 Calle 10-00 Zona 4 de Mixco, C.C. Naranjo Mall', '2433-9900', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-008');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-009', 'Peri-Roosevelt Zona 7', 'TIENDA', 'Calzada Roosevelt 25-50 Zona 7, C.C. Peri-Roosevelt', '2474-4455', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-009');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-010', 'Pacific Center Zona 11', 'TIENDA', 'Calzada Aguilar Batres 32-00 Zona 11', '2476-8899', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-010');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-011', 'Quetzaltenango Mont Blanc', 'TIENDA', '4ta Calle 18-01 Zona 3, Quetzaltenango', '7761-1234', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-011');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-012', 'Escuintla Palmeras', 'TIENDA', 'Km 60 Autopista Palín-Escuintla, C.C. Palmeras', '7889-5678', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-012');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-013', 'Antigua Guatemala Santa Inés', 'TIENDA', 'Calzada Santa Inés No. 8, Antigua Guatemala', '7832-9012', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-013');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-014', 'Cobán Plaza Magdalena', 'TIENDA', '1ra Calle 15-20 Zona 1, Cobán, Alta Verapaz', '7951-3456', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-014');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-015', 'Mazatenango Las Américas', 'TIENDA', 'Calzada Centenario Zona 2, Mazatenango', '7872-7890', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-015');

INSERT INTO NOM_SUCURSAL (CODIGO, NOMBRE, TIPO, DIRECCION, TELEFONO, ESTADO, ELIMINADO)
SELECT 'SUC-016', 'Chiquimula Pradera', 'TIENDA', 'Km 168 Ruta a Esquipulas, Chiquimula', '7942-2345', 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-016');

-- ----------------------------------------------------------------------------
-- NOMINA 4/4: Empleados EMP-001 a EMP-054
--   EMP-001..EMP-016: responsables de caja chica (uno por sucursal).
--   EMP-017..EMP-054: empleados adicionales por sucursal (combobox de
--   custodios filtrado por sucursal) y empleados que autorizan contrasenas.
-- ----------------------------------------------------------------------------
INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-001', 'Carlos Roberto', 'Gómez Morales', '2541987450101', '4587965-2', DATE '2023-01-15', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-001'), 'ADMINISTRATIVO', 5500.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-001');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-002', 'María Alejandra', 'López Estrada', '3012458790101', '9856321-4', DATE '2023-03-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-002'), 'ADMINISTRATIVO', 6000.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-002');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-003', 'Fernando José', 'Pineda Castillo', '1895623410101', '1245789-0', DATE '2022-08-10', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-003'), 'ADMINISTRATIVO', 8000.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-003');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-004', 'Ana Lucía', 'Méndez Morales', '2415896320101', '6589741-3', DATE '2023-05-12', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-004'), 'ADMINISTRATIVO', 5200.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-004');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-005', 'Héctor David', 'Ramírez Solís', '2987456120101', '3214569-8', DATE '2023-06-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-005'), 'ADMINISTRATIVO', 5800.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-005');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-006', 'Claudia Patricia', 'Barillas Fuentes', '2365897410101', '7412589-6', DATE '2022-11-20', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-006'), 'ADMINISTRATIVO', 5400.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-006');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-007', 'Rodrigo Alejandro', 'Samayoa Paz', '3125487960101', '8523697-1', DATE '2023-02-14', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-007'), 'ADMINISTRATIVO', 6100.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-007');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-008', 'Kimberly Vanessa', 'Alvarado Cruz', '2254789630101', '9632587-4', DATE '2023-04-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-008'), 'ADMINISTRATIVO', 5300.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-008');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-009', 'Edwin Gustavo', 'Carrera Ortiz', '2874561230101', '1478523-9', DATE '2022-09-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-009'), 'ADMINISTRATIVO', 5600.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-009');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-010', 'Sofía Isabel', 'Hernández Godoy', '3254189630101', '2589631-7', DATE '2023-07-15', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-010'), 'ADMINISTRATIVO', 5100.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-010');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-011', 'Javier Antonio', 'Villagrán Cifuentes', '2145896320901', '3698521-5', DATE '2022-05-10', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-011'), 'ADMINISTRATIVO', 5700.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-011');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-012', 'Sandra Maricela', 'Castillo De León', '2658974120501', '4789632-0', DATE '2023-01-20', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-012'), 'ADMINISTRATIVO', 5250.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-012');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-013', 'Luis Fernando', 'Montenegro Gálvez', '2789654120301', '5896321-8', DATE '2021-10-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-013'), 'ADMINISTRATIVO', 6300.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-013');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-014', 'Andrea Celeste', 'Quiñónez Vela', '3321458961601', '6985214-2', DATE '2023-08-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-014'), 'ADMINISTRATIVO', 5150.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-014');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-015', 'Manuel Enrique', 'Orellana Rivas', '2456987121001', '7896541-6', DATE '2022-12-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-015'), 'ADMINISTRATIVO', 5350.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-015');

INSERT INTO NOM_EMPLEADO ( CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO )
SELECT 'EMP-016', 'Karla Beatriz', 'Morales Solares', '2589632142001', '8963254-1', DATE '2023-09-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-016'), 'ADMINISTRATIVO', 5200.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-016');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-017', 'Jorge Mario', 'Valenzuela Ruiz', '2845123650101', '3456789-1', DATE '2023-04-10', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-001'), 'ADMINISTRATIVO', 5100.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-017');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-018', 'Brenda Elizabeth', 'Estrada Morales', '2956234780101', '4567890-2', DATE '2023-05-15', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-001'), 'ADMINISTRATIVO', 5300.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-018');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-019', 'Diego Armando', 'Cifuentes Paz', '2314567890101', '5678901-3', DATE '2023-06-20', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-001'), 'ADMINISTRATIVO', 4900.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-019');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-020', 'Kimberly Dayana', 'Reyes Soto', '2789456120101', '6789012-4', DATE '2023-02-18', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-002'), 'ADMINISTRATIVO', 5400.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-020');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-021', 'Julio César', 'Barrientos Lara', '2456789120101', '7890123-5', DATE '2022-11-05', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-002'), 'ADMINISTRATIVO', 5600.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-021');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-022', 'Patricia Eugenia', 'Castillo Monroy', '2145789630101', '8901234-6', DATE '2021-08-15', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-003'), 'ADMINISTRATIVO', 7200.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-022');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-023', 'Ricardo Antonio', 'Valladares Ochoa', '3124567890101', '9012345-7', DATE '2022-04-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-003'), 'ADMINISTRATIVO', 6800.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-023');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-024', 'Mónica Lucía', 'Arriola Fuentes', '2895623140101', '1123456-8', DATE '2023-01-10', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-003'), 'ADMINISTRATIVO', 6500.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-024');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-025', 'Erick Rolando', 'Gramajo Villatoro', '2678945120101', '2234567-9', DATE '2023-07-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-003'), 'ADMINISTRATIVO', 5900.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-025');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-026', 'Gerson David', 'Velásquez Cano', '2548963210101', '3345678-0', DATE '2023-03-22', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-004'), 'ADMINISTRATIVO', 5200.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-026');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-027', 'Wendy Paola', 'Girón Coronado', '2985632140101', '4456789-1', DATE '2023-05-02', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-005'), 'ADMINISTRATIVO', 5500.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-027');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-028', 'Álvaro Enrique', 'Menéndez Solórzano', '2415896320102', '5567890-2', DATE '2022-10-15', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-005'), 'ADMINISTRATIVO', 5700.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-028');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-029', 'Karen Alejandra', 'Tánchez Pinto', '3125896470101', '6678901-3', DATE '2023-08-11', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-005'), 'ADMINISTRATIVO', 5100.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-029');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-030', 'Otto René', 'Palacios Dávila', '2256987410101', '7789012-4', DATE '2023-01-18', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-006'), 'ADMINISTRATIVO', 5300.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-030');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-031', 'Evelyn Rocío', 'Marroquín Mejía', '2874125890101', '8890123-5', DATE '2023-06-05', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-006'), 'ADMINISTRATIVO', 5000.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-031');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-032', 'Hugo Leonel', 'Sagastume Paredes', '2365412890101', '9901234-6', DATE '2022-09-12', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-007'), 'ADMINISTRATIVO', 5800.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-032');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-033', 'Carmen Alicia', 'Donis Barahona', '2741852960101', '1012345-7', DATE '2023-02-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-007'), 'ADMINISTRATIVO', 5200.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-033');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-034', 'Walter Geovany', 'Chinchilla Solares', '3014785230101', '2123456-8', DATE '2023-04-15', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-007'), 'ADMINISTRATIVO', 5400.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-034');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-035', 'Nancy Gabriela', 'Rosales Godínez', '2589631470101', '3234567-9', DATE '2023-07-20', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-007'), 'ADMINISTRATIVO', 5050.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-035');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-036', 'Byron Estuardo', 'Salguero Lemus', '2941567820101', '4345678-0', DATE '2023-03-05', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-008'), 'ADMINISTRATIVO', 5300.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-036');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-037', 'Silvia Lorena', 'Colindres Archila', '2489654120101', '5456789-1', DATE '2023-01-25', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-009'), 'ADMINISTRATIVO', 5150.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-037');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-038', 'Marlon Steve', 'Orellana Cordon', '3258741230101', '6567890-2', DATE '2023-05-18', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-009'), 'ADMINISTRATIVO', 5450.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-038');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-039', 'Christian Alexander', 'Mazariegos Ovalle', '2154789630101', '7678901-3', DATE '2022-12-10', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-010'), 'ADMINISTRATIVO', 5100.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-039');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-040', 'Glenda Noemí', 'De la Roca Flores', '2896541230101', '8789012-4', DATE '2023-03-14', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-010'), 'ADMINISTRATIVO', 5350.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-040');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-041', 'Josué Daniel', 'Melgar Barrios', '3025874190101', '9890123-5', DATE '2023-06-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-010'), 'ADMINISTRATIVO', 4950.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-041');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-042', 'Miriam Azucena', 'Rodas Xicay', '2415896320901', '1098765-6', DATE '2022-06-15', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-011'), 'ADMINISTRATIVO', 5600.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-042');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-043', 'Wilson Omar', 'Sacalxot Gómez', '2896541230901', '2109876-7', DATE '2023-01-10', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-011'), 'ADMINISTRATIVO', 5400.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-043');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-044', 'Lesly Marleni', 'Quemé Cojulún', '3125487960901', '3210987-8', DATE '2023-04-05', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-011'), 'ADMINISTRATIVO', 5250.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-044');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-045', 'César Augusto', 'De León López', '2658974120901', '4321098-9', DATE '2023-07-22', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-011'), 'ADMINISTRATIVO', 5750.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-045');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-046', 'Jennifer Paola', 'Monterroso Duarte', '2789654120501', '5432109-0', DATE '2023-05-30', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-012'), 'ADMINISTRATIVO', 5200.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-046');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-047', 'Gilberto Ernesto', 'Vivar Asturias', '2365897410301', '6543210-1', DATE '2022-10-01', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-013'), 'ADMINISTRATIVO', 5900.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-047');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-048', 'Diana Carolina', 'Celada Vides', '3254189630301', '7654321-2', DATE '2023-03-15', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-013'), 'ADMINISTRATIVO', 5400.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-048');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-049', 'Ramiro Alfonso', 'Pop Caal', '2589632141601', '8765432-3', DATE '2022-07-20', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-014'), 'ADMINISTRATIVO', 5300.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-049');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-050', 'Mayra Jeannette', 'Chen Winter', '2874561231601', '9876543-4', DATE '2023-02-12', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-014'), 'ADMINISTRATIVO', 5100.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-050');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-051', 'Kevin Oswaldo', 'Sierra Macz', '3125487961601', '1987654-5', DATE '2023-06-18', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-014'), 'ADMINISTRATIVO', 4950.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-051');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-052', 'Rudy Francisco', 'Villatoro Maldonado', '2415896321001', '2098765-6', DATE '2023-04-28', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-015'), 'ADMINISTRATIVO', 5150.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-052');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-053', 'Elsa Marina', 'Suchité Trabanino', '2789654122001', '3109876-7', DATE '2023-01-15', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-016'), 'ADMINISTRATIVO', 5000.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-053');

INSERT INTO NOM_EMPLEADO (CODIGO_EMPLEADO, NOMBRES, APELLIDOS, DPI, NIT, FECHA_INGRESO, ID_PUESTO, ID_DEPARTAMENTO, ID_SUCURSAL, TIPO_EMPLEADO, SALARIO_BASE, ESTADO, ELIMINADO)
SELECT 'EMP-054', 'Héctor Manuel', 'España Guerra', '2956234782001', '4210987-8', DATE '2023-05-20', (SELECT MIN(ID_PUESTO) FROM NOM_PUESTO WHERE NOMBRE = 'Encargado de Tienda / Custodio'), (SELECT MIN(ID_DEPARTAMENTO) FROM NOM_DEPARTAMENTO WHERE NOMBRE = 'Administración y Finanzas'), (SELECT ID_SUCURSAL FROM NOM_SUCURSAL WHERE CODIGO = 'SUC-016'), 'ADMINISTRATIVO', 5250.00, 'A', 'N'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NOM_EMPLEADO WHERE CODIGO_EMPLEADO = 'EMP-054');

COMMIT;

-- ----------------------------------------------------------------------------
-- COMPRAS: Proveedores (Facturas Proveedor los busca por NIT)
--   El ultimo esta INACTIVO a proposito: no debe aparecer en el selector.
-- ----------------------------------------------------------------------------
MERGE INTO PROVEEDOR d
USING (
    SELECT '1234567-8' NIT, 'Papelería y Suministros El Estudiante, S.A.' RAZON_SOCIAL, 'El Estudiante' NOMBRE_COMERCIAL,
           '7a. Avenida 12-45 Zona 1, Guatemala' DIRECCION, '2232-1100' TELEFONO, 'ventas@elestudiante.com.gt' EMAIL,
           30 DIAS_CREDITO, 'A' CALIFICACION, '012-345678-9' CUENTA_BANCARIA, 'Banco Industrial' BANCO, 'A' ESTADO FROM DUAL UNION ALL
    SELECT '2345678-9', 'Distribuidora de Papel Térmico GT, S.A.', 'PapelTerm GT',
           'Calzada San Juan 15-20 Zona 7, Guatemala', '2440-2200', 'pedidos@papeltermgt.com', 15, 'A', '044-112233-0', 'Banco G&T Continental', 'A' FROM DUAL UNION ALL
    SELECT '3456789-0', 'Servicios de Limpieza Integral, S.A.', 'Limpieza Integral',
           '18 Calle 5-30 Zona 10, Guatemala', '2366-3300', 'contacto@limpiezaintegral.gt', 30, 'B', '301-998877-1', 'Banrural', 'A' FROM DUAL UNION ALL
    SELECT '4567890-1', 'Consultores en Auditoría Informática', 'AudiTI Consultores',
           '6a. Avenida 9-18 Zona 9, Guatemala', '2331-4400', 'info@auditi.gt', 45, 'A', '055-667788-2', 'Banco Agromercantil (BAM)', 'A' FROM DUAL UNION ALL
    SELECT '5678901-2', 'Tecnología y Almacenamiento, S.A.', 'TecnoStore',
           'Boulevard Liberación 6-31 Zona 9, Guatemala', '2385-5500', 'ventas@tecnostore.com.gt', 60, 'A', '012-554433-3', 'Banco Industrial', 'A' FROM DUAL UNION ALL
    SELECT '6789012-3', 'Software Contable de Guatemala, S.A.', 'ContaSoft',
           '12 Calle 1-25 Zona 10, Edificio Géminis', '2299-6600', 'licencias@contasoft.gt', 30, 'A', '044-221100-4', 'Banco G&T Continental', 'A' FROM DUAL UNION ALL
    SELECT '7890123-4', 'Transportes y Logística Rápida, S.A.', 'TransRápida',
           'Km 17.5 Carretera al Pacífico, Villa Nueva', '6630-7700', 'operaciones@transrapida.gt', 15, 'B', '301-445566-5', 'Banrural', 'A' FROM DUAL UNION ALL
    SELECT '8901234-5', 'Proveedor Inactivo de Prueba, S.A.', 'Inactivo',
           'Sin dirección', '0000-0000', NULL, 0, 'C', NULL, NULL, 'I' FROM DUAL
) s
ON (d.NIT = s.NIT)
WHEN NOT MATCHED THEN
    INSERT (NIT, RAZON_SOCIAL, NOMBRE_COMERCIAL, DIRECCION, TELEFONO, EMAIL, DIAS_CREDITO, CALIFICACION, CUENTA_BANCARIA, BANCO, ESTADO)
    VALUES (s.NIT, s.RAZON_SOCIAL, s.NOMBRE_COMERCIAL, s.DIRECCION, s.TELEFONO, s.EMAIL, s.DIAS_CREDITO, s.CALIFICACION, s.CUENTA_BANCARIA, s.BANCO, s.ESTADO);

COMMIT;

-- ----------------------------------------------------------------------------
-- INVENTARIOS: Categorias y articulos (lineas de factura los buscan por CODIGO)
-- ----------------------------------------------------------------------------
MERGE INTO CATEGORIA_ARTICULO d
USING (
    SELECT 'Suministros de Oficina' NOMBRE FROM DUAL UNION ALL
    SELECT 'Equipo de Cómputo' FROM DUAL UNION ALL
    SELECT 'Software y Licencias' FROM DUAL UNION ALL
    SELECT 'Insumos de Punto de Venta' FROM DUAL
) s
ON (d.NOMBRE = s.NOMBRE)
WHEN NOT MATCHED THEN INSERT (NOMBRE) VALUES (s.NOMBRE);

MERGE INTO ARTICULO d
USING (
    SELECT 'ART-2001' CODIGO, 'Resma de papel bond carta' NOMBRE, 'Suministros de Oficina' CATEGORIA,
           'Paquete' UNIDAD_MEDIDA, 'MATERIAL_USO_INTERNO' TIPO_ARTICULO, 150 COSTO FROM DUAL UNION ALL
    SELECT 'ART-2003', 'Bobina de papel térmico 80mm', 'Insumos de Punto de Venta', 'Rollo', 'MATERIAL_USO_INTERNO', 100 FROM DUAL UNION ALL
    SELECT 'ART-2006', 'Servidor de almacenamiento NAS 16TB', 'Equipo de Cómputo', 'Unidad', 'ACTIVO_FIJO', 4000 FROM DUAL UNION ALL
    SELECT 'ART-2007', 'Licencia anual de software contable', 'Software y Licencias', 'Unidad', 'MATERIAL_USO_INTERNO', 1400 FROM DUAL UNION ALL
    SELECT 'ART-2009', 'Tóner para impresora láser', 'Suministros de Oficina', 'Unidad', 'MATERIAL_USO_INTERNO', 450 FROM DUAL
) s
ON (d.CODIGO = s.CODIGO)
WHEN NOT MATCHED THEN
    INSERT (CODIGO, NOMBRE, ID_CATEGORIA, UNIDAD_MEDIDA, TIPO_ARTICULO, COSTO_PROMEDIO, ESTADO)
    VALUES (s.CODIGO, s.NOMBRE, (SELECT MIN(ID_CATEGORIA) FROM CATEGORIA_ARTICULO WHERE NOMBRE = s.CATEGORIA),
            s.UNIDAD_MEDIDA, s.TIPO_ARTICULO, s.COSTO, 'A');

COMMIT;

PROMPT Dependencias externas cargadas: 4 departamentos, 5 puestos, 16 sucursales,
PROMPT 54 empleados, 8 proveedores (1 inactivo), 4 categorias y 5 articulos.
